### ISSUE TITLE
for Tissue trajectory analysis,

### ISSUE THREAD

**Issue by yingfang3333** [BiomedicalMachineLearning/stLearn#107]
Dear developer:
Thank you for building the useful pipline but I confuse about thoes fellowing questions:
If I want analyze tissue trajectory by the Annotated data that has been ran by 'spatial.SME.SME_normalize' and 'tl.clustering.louvain', is  'spatial.morphology.adjust' and 'tl.clustering.louvain' still needed?

**Comment by duypham2108** [comment]
Thanks for using our tool.

My answer is no. If you are already done the SME normalisation and the Louvain clustering, then you can start to apply the spatial trajectory inference from this step: [2. Spatial trajectory inference](https://stlearn.readthedocs.io/en/latest/tutorials/Pseudo-time-space-tutorial.html#2.-Spatial-trajectory-inference).
