### ISSUE TITLE
Spatial trajectory inference,when I use stlearn to do seurat cluster ,It meet  a mistake? 

### ISSUE THREAD

**Issue by hzaumsq** [BiomedicalMachineLearning/stLearn#110]
import numpy as np
data.uns["iroot"] = np.flatnonzero(data.obs["Seurat"]  == str(1))[0]
st.spatial.trajectory.pseudotime(data,eps=50,use_rep="X_pca")
st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=[1,2,3,4])

![微信图片_20210419172900](https://user-images.githubusercontent.com/34264027/115214381-08ecb000-a135-11eb-9080-38dfdae217e5.png)

**Comment by duypham2108** [comment]
We have already fixed the problem of the order of the cluster name but haven't published it yet. We will publish the new version next week.
One way to fix your problem is that you need to rename the cluster:

```
data.obs["Seurat"].cat.categories = ["0","1","2","3","4"]

# And then your code but change a little bit about the order
import numpy as np
data.uns["iroot"] = np.flatnonzero(data.obs["Seurat"] == str(0))[0]
st.spatial.trajectory.pseudotime(data,eps=50,use_rep="X_pca")
st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=[0,1,2,3])
```
Also, I recommend you test a spatial trajectory path with two clusters first.

Hope it helps.

**Comment by hzaumsq** [comment]
Screening:   0%|           [ time left: ? ]
Screening PTS global graph...
Screening:   0%|           [ time left: ? ]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-75-286ffc343a70> in <module>
      2 #data.uns["iroot"] = np.flatnonzero(data.obs["Seurat"]  == str(1))[0]
      3 #st.spatial.trajectory.pseudotime(data,eps=50,use_rep="X_pca")
----> 4 st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=[1,2,3])
      5 #st.spatial.trajectory.pseudotimespace_global(data,use_label="louvain",list_clusters=[10,6,8,3])
      6 #st.spatial.trajectory.pseudotimespace_local(data,use_label="Seurat",list_clusters=[1,2]))

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\pseudotimespace.py in pseudotimespace_global(adata, use_label, list_clusters, w, step, k)
     39     if w is None:
     40 
---> 41         w = weight_optimizing_global(
     42             adata, use_label=use_label, list_clusters=list_clusters, step=step, k=k
     43         )

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\weight_optimization.py in weight_optimizing_global(adata, use_label, list_clusters, step, k)
     25             Gs.append(
     26                 nx.adjacency_matrix(
---> 27                     global_level(
     28                         adata,
     29                         use_label=use_label,

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\global_level.py in global_level(adata, use_label, list_clusters, return_graph, w, verbose, copy)
    116     for edge, _ in labels.items():
    117 
--> 118         dm = dm_list[order_big_dict[query_dict[edge[0]]]]
    119         sdm = sdm_list[order_big_dict[query_dict[edge[0]]]]
    120 

KeyError: 5

**Comment by duypham2108** [comment]
I think you need to change the order of the "Seurat" cluster to 0 to 4 rather than [1,2,3,4,9] (Like what I show in the previous comment). As I said, it's the order of cluster name problem.

Another way to fix it is to install the GitHub version (you may need to uninstall the older version first by `pip uninstall stlearn`:

```
git clone https://github.com/BiomedicalMachineLearning/stLearn.git
cd stLearn
python setup.py install
```
 And then you can use `list_cluster` as a list of string:
```
st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=["1","2","3"])
```

**Comment by hzaumsq** [comment]
I had do as you have recommended, but also can't get a trajectory ? if it has  the big difference among the subcluster  to be constructed?  
Screening:   0%|           [ time left: ? ]
Screening PTS global graph...

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-0a394d106ba9> in <module>
----> 1 st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=["1","2","3"])
      2 #st.spatial.trajectory.pseudotimespace_global(data,use_label="louvain",list_clusters=[2,3,4])
      3 #st.pl.cluster_plot(data,use_label="louvain",show_trajectories=True,list_clusters=[2,3,4],show_subcluster=True)
      4 
      5 #st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=[2,3,4])

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\pseudotimespace.py in pseudotimespace_global(adata, use_label, list_clusters, w, step, k)

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\weight_optimization.py in weight_optimizing_global(adata, use_label, list_clusters, step, k)

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\global_level.py in global_level(adata, use_label, list_clusters, return_graph, w, verbose, copy)

**Comment by hzaumsq** [comment]
> I had do as you have recommended, but also can't get a trajectory ? if it has the big difference among the subcluster to be constructed?
> Screening: 0%| [ time left: ? ]
> Screening PTS global graph...
> 
> KeyError Traceback (most recent call last)
> in
> ----> 1 st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=["1","2","3"])
> 2 #st.spatial.trajectory.pseudotimespace_global(data,use_label="louvain",list_clusters=[2,3,4])
> 3 #st.pl.cluster_plot(data,use_label="louvain",show_trajectories=True,list_clusters=[2,3,4],show_subcluster=True)
> 4
> 5 #st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=[2,3,4])
> 
> ~.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\pseudotimespace.py in pseudotimespace_global(adata, use_label, list_clusters, w, step, k)
> 
> ~.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\weight_optimization.py in weight_optimizing_global(adata, use_label, list_clusters, step, k)
> 
> ~.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\global_level.py in global_level(adata, use_label, list_clusters, return_graph, w, verbose, copy)
