### ISSUE TITLE
I had do as you have recommended, but also can't get a trajectory ? if it has  the big difference among the subcluster  to be constructed?

### ISSUE THREAD

**Issue by hzaumsq** [BiomedicalMachineLearning/stLearn#111]
I had do as you have recommended, but also can't get a trajectory ? if it has  the big difference among the subcluster  to be constructed?  
Screening:   0%|           [ time left: ? ]
Screening PTS global graph...

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-0a394d106ba9> in <module>
----> 1 st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=["1","2","3"])
      2 #st.spatial.trajectory.pseudotimespace_global(data,use_label="louvain",list_clusters=[2,3,4])
      3 #st.pl.cluster_plot(data,use_label="louvain",show_trajectories=True,list_clusters=[2,3,4],show_subcluster=True)
      4 
      5 #st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=[2,3,4])

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\pseudotimespace.py in pseudotimespace_global(adata, use_label, list_clusters, w, step, k)

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\weight_optimization.py in weight_optimizing_global(adata, use_label, list_clusters, step, k)

~\.conda\envs\stlearn\lib\site-packages\stlearn\spatials\trajectory\global_level.py in global_level(adata, use_label, list_clusters, return_graph, w, verbose, copy)

_Originally posted by @hzaumsq in https://github.com/BiomedicalMachineLearning/stLearn/issues/110#issuecomment-822448881_

**Comment by hzaumsq** [comment]
![image](https://user-images.githubusercontent.com/34264027/115241574-8fb08580-a153-11eb-9dd4-a2e31725a7f0.png)

**Comment by duypham2108** [comment]
Can you show me the result of this?
```
print(data.obs["Seurat"])
```

**Comment by hzaumsq** [comment]
![Uploading image.png…]()

**Comment by hzaumsq** [comment]
> Can you show me the result of this?
> 
> ```
> print(data.obs.Seurat.cat.categories)
> ```

![image](https://user-images.githubusercontent.com/34264027/115241868-e0c07980-a153-11eb-890e-2766dd128152.png)

**Comment by duypham2108** [comment]
In the new version of stlearn, KeyError only happens when there is no cluster name.
I think the issue here may be the lack of show `use_label` when initializing the pseudotime. Can you run this one again with the `use_label` = "Seurat". It now automatically sets as "louvain". We will change it in the next version. It should be required the user input that parameter.

```
st.spatial.trajectory.pseudotime(data,eps=50,use_rep="X_pca",use_label="Seurat)
# For the new version
st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=["1","2","3"])
```

**Comment by hzaumsq** [comment]
![image](https://user-images.githubusercontent.com/34264027/115244900-f71c0480-a156-11eb-9ea5-12715f909416.png)
![image](https://user-images.githubusercontent.com/34264027/115244956-0733e400-a157-11eb-9d34-bef221ea073f.png)

**Comment by duypham2108** [comment]
That's weird.
Let try different options:
**Option 1:**
To make sure you install the latest version, you can run this code:
```
data.uns["Seurat_index_dict"]
```
It will give you a dictionary of cluster indexes. You can run both [1,2,3] and ["1","2","3"].
If you don't see it, you may need to uninstall and install the GitHub version again.

**Option 2:**
If the order of data.obs["Seurat"] is refined, then you also can run (it should work):
```
st.spatial.trajectory.pseudotimespace_global(data,use_label="Seurat",list_clusters=[1,2,3])
```
I will try to test different cases to see there is any other issue that may be happened. I will be back tomorrow if you still have this issue. Sorry for that.
