### ISSUE TITLE
Function of interactive not works

### ISSUE THREAD

**Issue by jipeifeng** [BiomedicalMachineLearning/stLearn#113]
Dear developer:
     Thank you for the great tool. I am using it on my dataset, but came across an issue about the interactive function.
      The code of 'st.pl.gene_plot_interactive' doest not result in the interactive plots.

<img width="1021" alt="截屏2021-04-25 下午5 42 49" src="https://user-images.githubusercontent.com/24560774/115988738-b1938780-a5ed-11eb-86c7-c60160069999.png">

     To confirm whether the bokeh package works, I have tested it.
   
<img width="914" alt="截屏2021-04-25 下午4 27 06" src="https://user-images.githubusercontent.com/24560774/115986560-5361a700-a5e3-11eb-8022-e6eb3c10c246.png">

 So, could you please find it out!

Thank your!

Peifeng

**Comment by duypham2108** [comment]
Thanks for reporting this issue.

First of all, this function will host a bokeh app by the bokeh server then it will meet a problem if the jupyter doesn't allow bokeh to use this web socket.

In the os terminal, "set" for windows and "export" for linux/macos before you run the jupyter notebook/lab:

```
set BOKEH_ALLOW_WS_ORIGIN=localhost:8889
export BOKEH_ALLOW_WS_ORIGIN=localhost:8889
```

Other things you can do if you still meet this problem:

If you are using Jupyter lab, please try this and restart the jupyter lab:

```
conda install jupyter_bokeh
```

Also, we are currently supporting the interactive version in the local machine (jupyter notebook/lab on your computer) only. Just make sure you don't use JupyterHub (we will try to support it in the near future).

If you can fix it, I will make a warning in the tutorial.

**Comment by jipeifeng** [comment]
Thanks you! 
The solution above fixed the bug of interactive, but the problem are not fully addressed.
Specifically, I can not interactively  explore the gene expression pattern.
<img width="990" alt="截屏2021-04-26 上午9 09 56" src="https://user-images.githubusercontent.com/24560774/116016434-2e1a7a80-a66f-11eb-8c83-cec5704675b0.png">

However, I can explore the expression using the gene_plot function:
![Uploading 截屏2021-04-26 上午9.10.37.png…]()





PS: my operating system is MACOS and I have run the jupyter lab for data mining.

**Comment by duypham2108** [comment]
I found it's an issue for all non-visium data. One reason may be the XY coordinates of your data is too large/small then it cannot display in the notebook.

One way to fix it is that you add the parameter `scale` when you create or read the non-visium data. You should use `scale` < 1 when it's too large or `scale` > 1 when it's too small. The final maximum value for coordinates should be around 2000. You can check by `np.max(adata.obs[["imagecol","imagerow"]])` .

We will try to auto-scale it in the next update for non-visium data.

**Comment by davisidarta** [comment]
I've come across the same issue and spent a considerable amount of time trying to address it. I had thought it was a problem with Bokeh at first. Setting the `scale` parameter to `0.1` worked well in my case (VizGen data). Maybe this could be further highlighted in the tutorials?
