### ISSUE TITLE
problem on running st.pl.trajectory.pseudotime_plot

### ISSUE THREAD

**Issue by zhengdongfeng** [BiomedicalMachineLearning/stLearn#130]
Hi, thanks for your helpful tool so much. But I encounter an error when I running `st.pl.trajectory.pseudotime_plot`, my data is divided into 12 clusters, I have done some tries on modifying "list_clusters" option, but still failed. Below is some of my result, can you give me some suggestions? My stlearn version is 0.3.1. 
![1](https://user-images.githubusercontent.com/58932073/132432612-7b50de98-a7be-44b2-afd7-0527a43c6579.png)
![3](https://user-images.githubusercontent.com/58932073/132432611-4d0f10f5-0655-43ef-a50b-d2b8b1c090df.png)
![4](https://user-images.githubusercontent.com/58932073/132432629-c4910e9d-e17e-45a4-99b6-b4479b32ae0b.png)
![5](https://user-images.githubusercontent.com/58932073/132432644-37d1af73-4e5e-430c-8616-e37fee14b145.png)
![6](https://user-images.githubusercontent.com/58932073/132432655-631e413b-709b-4bd3-9408-906597db156e.png)

**Comment by duypham2108** [comment]
Sorry for that. Can you please clone this repository? and install the git version by `python setup.py install` and run your code again.

I will be free after next couple hours then I can help you in detail after that.

**Comment by duypham2108** [comment]
The split_node contains a dictionary with key is the main cluster and values are the list of sub-clusters that separated based on their location.
