### ISSUE TITLE
problem about finding file "label_transfer_bc.csv"

### ISSUE THREAD

**Issue by zhengdongfeng** [BiomedicalMachineLearning/stLearn#132]
Hi, I'm very interested in your tool stlearn. I am studying to do some Cell-cell interaction analysis  following your tutorial, but I cannot find the file "label_transfer_bc.csv", can you tell me where I can find it or can you provide it to me directly? Thanks in advance.
![微信截图_20210909191834](https://user-images.githubusercontent.com/58932073/132676645-91959c30-310f-4692-8f1c-f16d96cd0745.png)

**Comment by jon-xu** [comment]
Hi Dongfeng,

this is the result of seurat label transfer.

Cheers,
Jon

**Comment by zhengdongfeng** [comment]
Thanks. But how can I find this file as your tutorial shows.

**Comment by zhengdongfeng** [comment]
Thank you so much that I have found it.

**Comment by zhengdongfeng** [comment]
Hi, I'm sorry to bother you again. When I run `st.add.labels(data, './label_transfer_bc.csv', sep='\t')`, there is an error shown as below, in this csv file, I can find "predicted.id" header, but not "prediction.score.max", I'm not sure whether the error is because of that. Can you give me some advices? Thank you very much.

> ---------------------------------------------------------------------
KeyError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_30664/1074072774.py in <module>
----> 1 st.add.labels(data, './label_transfer_bc.csv', sep='\t')

~\anaconda3\envs\stlearn\lib\site-packages\stlearn\adds\add_labels.py in labels(adata, label_filepath, index_col, sep, copy)
     31     """
     32     labels = pd.read_csv(label_filepath, index_col=index_col, sep=sep)
---> 33     adata.uns["label_transfer"] = labels.drop(
     34         ["predicted.id", "prediction.score.max"], axis=1
     35     )

~\anaconda3\envs\stlearn\lib\site-packages\pandas\util\_decorators.py in wrapper(*args, **kwargs)
    309                     stacklevel=stacklevel,
    310                 )
--> 311             return func(*args, **kwargs)
    312 
    313         return wrapper

~\anaconda3\envs\stlearn\lib\site-packages\pandas\core\frame.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   4899                 weight  1.0     0.8
   4900         """
-> 4901         return super().drop(
   4902             labels=labels,
   4903             axis=axis,

~\anaconda3\envs\stlearn\lib\site-packages\pandas\core\generic.py in drop(self, labels, axis, index, columns, level, inplace, errors)
   4148         for axis, labels in axes.items():
   4149             if labels is not None:
-> 4150                 obj = obj._drop_axis(labels, axis, level=level, errors=errors)
   4151 
   4152         if inplace:

~\anaconda3\envs\stlearn\lib\site-packages\pandas\core\generic.py in _drop_axis(self, labels, axis, level, errors)
   4183                 new_axis = axis.drop(labels, level=level, errors=errors)
   4184             else:
-> 4185                 new_axis = axis.drop(labels, errors=errors)
   4186             result = self.reindex(**{axis_name: new_axis})
   4187 

~\anaconda3\envs\stlearn\lib\site-packages\pandas\core\indexes\base.py in drop(self, labels, errors)
   6016         if mask.any():
   6017             if errors != "ignore":
-> 6018                 raise KeyError(f"{labels[mask]} not found in axis")
   6019             indexer = indexer[~mask]
   6020         return self.delete(indexer)

**KeyError: "['predicted.id' 'prediction.score.max'] not found in axis"**

**Comment by jon-xu** [comment]
the "prediction.score.max" field is there in the sample file and st.add.labels works fine.

**Comment by zhengdongfeng** [comment]
Thank you, I saw  "prediction.score.max" field, but I just don't know why I encountered this error, can you give me some advices?

**Comment by jinyuanchun** [comment]
> https://github.com/BiomedicalMachineLearning/stLearn/blob/master/tutorials/label_transfer_bc.csv

hi,can you give me the five ,because the link is not exists

**Comment by duypham2108** [comment]
@jinyuanchun here is the file, we will move this file to another location
https://github.com/BiomedicalMachineLearning/stLearn/blob/5e4c966f99ecdfcb568f0b735929163f6cac2a1c/tutorials/label_transfer_bc.csv

**Comment by jinyuanchun** [comment]
> @jinyuanchun here is the file, we will move this file to another location https://github.com/BiomedicalMachineLearning/stLearn/blob/5e4c966f99ecdfcb568f0b735929163f6cac2a1c/tutorials/label_transfer_bc.csv

thank u
