### ISSUE TITLE
st.pl.deconvolution_plot() size error

### ISSUE THREAD

**Issue by lsudupe** [BiomedicalMachineLearning/stLearn#138]
When I use this function, I get a perfect scatter pie plot but the donut chart is supermini, I can´t even see it. I try with different samples and always I am getting the same plot sizes.

What could it be?

This is the code
st.pl.deconvolution_plot(data,threshold=0.1,spot_size=30)

**Comment by duypham2108** [comment]
I have already fix this in the github version #125 . 
Can you please install directly from github?
```
git clone https://github.com/BiomedicalMachineLearning/stLearn.git
cd stLearn
python setup.py install
```
