### ISSUE TITLE
Problem when reproducing Cell-to-cell Interaction Part

### ISSUE THREAD

**Issue by YistYU** [BiomedicalMachineLearning/stLearn#141]
Hi,

As I'm trying to reproduce the result by following the tutorials of the Cell-to-cell Interaction part, there are some problems for the step of "Ligand-receptor co-expression (between-spots)".

I followed the input strictly, and can successfully reproduce the images for the step of "Count cell type diversity (between-spots)". But, when going to LR co-expression analysis, the output will be null.

The h5 file I downloaded for C2C interaction is from the URL below:
"https://www.dropbox.com/s/0o10xzan58ln38o/example_bcba.h5"

I checked the original codes and found that under the "tutorials" folder there are some data about LR-pairs. So is there any additional information is required for my downloaded h5 file or any clue about how I can learn more about the reproducing of results?

Many thanks!!

**Comment by BradBalderson** [comment]
Hi YistYu, 

Just back at it after a few weeks off, so apologies for the late reply.

@jon-xu is back soon as well & wrote this part of analysis so will leave this one to him :).

In the meantime though, would you mind providing more information about the output so we can see exactly what's going wrong?

Thanks alot
