### ISSUE TITLE
Something wrong in plot

### ISSUE THREAD

**Issue by anchormok** [BiomedicalMachineLearning/stLearn#143]

**Comment by anchormok** [comment]
Dear developer，

Thanks for your great work and package. I have run this package recently and found some errors.

import stlearn as st
st.settings.set_figure_params(dpi=180)
In:

Is it expecting me to give some further input and whatever I tried does not work.


And When I run some plot function, such as "st.pl.cluster_plot", no figure has generated.
Also, when I run "st.pl.gene.interactive", no window has generated and just like "In:"

![微信截图_20211225142933](https://user-images.githubusercontent.com/40140273/147378956-f4da27b1-b877-48a0-ad21-61bfc0ae47bb.jpg)

**Comment by duypham2108** [comment]
Currently, we only focus on using this toolkit in jupyter environment. For the settings, it will open the IPython then you will see the "In:" prompt. If you still want to use the console like this, you can show the plot by this code after you run the `st.pl.cluster_plot`:

```
import matplotlib.pyplot as plt
plt.show()
```
For the interactive version, it required javascript then only jupyter in chrome can work. I hope you can use the jupyter notebook/lab for this toolkit.

**Comment by anchormok** [comment]
Thanks a lot for your reply!!

Your answers help me a lot. And I tried to use jupyter notebook to run stlearn.

However, after running the code "st.pl.gene_plot_interactive", no interactive window was presented. I confirmed that I have installed the "ipywidgets" package.

![1226](https://user-images.githubusercontent.com/40140273/147402322-7c3b57ac-bcf8-45c9-ba13-2145fe5b594e.jpg)

How can I solve this problem?
Thank you very much!!

**Comment by duypham2108** [comment]
Can you check the port that you run the jupyter notebook?
Currently, I set the default port as :8888 (you should have the same port with your jupyter notebook).

If your port is :8888, then after you run `st.pl.gene_plot_interactive(data_SME)`, please press F12 and in the Console tab, please send me the error there.

**Comment by anchormok** [comment]
OK, I have confirmed that the port I used was 8888.

According to your suggestions, the errors occurred as follow:
![1227](https://user-images.githubusercontent.com/40140273/147429510-57bc6b06-2ece-41a6-bffd-208ecb610821.jpg)

Thanks again for your help!

**Comment by duypham2108** [comment]
It's the problem of remotely host. I have developed the interactive function as the Bokeh app which hosts in the local. The port will look like `localhost:8888`. Sorry that it cannot be run like yours.

You should run the jupyter notebook in your local to use it.
