### ISSUE TITLE
DLL load failed while importing utilsextension

### ISSUE THREAD

**Issue by bioinflix** [BiomedicalMachineLearning/stLearn#146]
Hi, I successfully installed stLearn (windows system). But when I decided to try this tool following the turorial, it occurred this problem: "DLL load failed while importing utilsextension".

I also uninstalled the tables and install tables again following the suggestion provided in the installation page, but the problem still appearred.

Could you please help fix this error?

**Comment by duypham2108** [comment]
We mention this bug here: `https://stlearn.readthedocs.io/en/latest/installation.html`
You can scroll down to the bottom to see it.

**Comment by bioinflix** [comment]
> We mention this bug here: https://stlearn.readthedocs.io/en/latest/installation.html You can scroll down to the bottom to see it.

Yes, actually I have followed this suggestion by uninstalling and installing tables again, but the error still occurred.

**Comment by bioinflix** [comment]
I have install the tables again and the error was not shown as before. But there was a new error raised as below:

"ImportError: numpy.core.multiarray failed to import"

I have struggled for this error by installing numpy and stlearn for several times, but without any solution. I think this problem comes from the version incompatibility for different mocules. stLearn 0.3.2 requires tensorflow==2.4.0, tensorflow 2.4.0 requires numpy~=1.19.2, but installing numpy 1.19.2 could generate the import error above.

Could you please send me the enviroment requirements (including versions) for stlearn (0.3.2)?

By the way, I could not find the exact igraph and louvain files (python_igraph‑0.7.1.post6‑cp38‑cp38‑win_amd64.whl and louvain‑0.6.1‑cp38‑cp38‑win_amd64.whl) suggested in the installation page from the website, so I installed them by:
pip install python-igraph
pip install python-louvain

But the versions are: python-igraph 0.9.9; python-louvain: 0.15. I hope this should not be the problem.

Thanks!

**Comment by duypham2108** [comment]
The best way to install now is the github version. We plan to release it this month, but you can clone the github and install by:
```
pip uninstall stlearn
python setup.py install
```

I think it will solve the version problem.
