### ISSUE TITLE
Error when using K-means clustering on stSME

### ISSUE THREAD

**Issue by peicai** [BiomedicalMachineLearning/stLearn#151]
Hi,

I'm trying to follow the stSME clustering tutorial. Then I got the following error "TypeError: __init__() got an unexpected keyword argument 'precompute_distances'" when I applied "st.tl.clustering.kmeans" function. I've successfully run the code two or three months ago but failed these days. Could you please help fix this error? Thanks in advance!

Attached are the codes and the traceback.
<img width="834" alt="Screen Shot 2022-01-26 at 9 34 42 PM" src="https://user-images.githubusercontent.com/55488976/151242935-55c97df5-acfd-429d-b1ee-c55cd9692202.png"> 
<img width="1055" alt="Screen Shot 2022-01-26 at 9 34 53 PM" src="https://user-images.githubusercontent.com/55488976/151242944-9d466992-aa92-49f9-bec6-c3b7a6569037.png">

**Comment by duypham2108** [comment]
Thanks for your report. We fixed it. You can install the github version to update it.
Commit: a5c1ee6f5ef3c97d89bab46cf88054889a0f2cac

**Comment by peicai** [comment]
Thanks! It works.
