### ISSUE TITLE
How use `gene_plot` to show continuous columns in `adata.obs`

### ISSUE THREAD

**Issue by eleozzr** [BiomedicalMachineLearning/stLearn#156]
Great tool! 
st.pl.gene_plots shows nicely figures for gene_symbol in `adata.var_names`, but i don't know how to show the continuous columns in adata.obs_names. scanpy can use (sc.pl.scatter(adata,color="nGenes") to show the gene_symbol in adata.var_names and clusters in adata.obs_names. 

Although I implemented it in a native way (replace one gene's expression with continuous columns in adata.obs_names), it is not convenient.
```
#The first item in adata.var_names is `Xkr4`
adata_tmp1.X[:,0]=adata_tmp1.obs['score'].values
st.pl.gene_plot(adata_tmp1,gene_symbols="Xkr4",crop=False, size=1.4,cell_alpha=1,contour=True)
```

So is there a more convenient way to show the continuous plots with the parameter `contour=True`

**Comment by duypham2108** [comment]
We implemented feature plot in the lastest version 0.4.5 for plotting continous variable in `adata.obs`. I think it will solve the issue

```
st.pl.feat_plot(adata, feature="feature", contour=True)
```
