### ISSUE TITLE
Errors in running st.tl.cci.run

### ISSUE THREAD

**Issue by anchormok** [BiomedicalMachineLearning/stLearn#157]
Dear developer，

I have used stLearn to explore the cell interaction, however, when I run function "st.tl.cci.run", the errors occurred.

![20220312181942](https://user-images.githubusercontent.com/40140273/158014276-61ae861a-726e-4a75-bc69-109d65f45aac.jpg)

Is the version of numba incompatible with stLearn?

Or other problems?

Looking forward to your reply!

Thank you very much!

**Comment by duypham2108** [comment]
It's probably the issue of numba. Can you send me the version of numba? It works well with 0.55.1

**Comment by anchormok** [comment]
Thanks for your reply.

The numba in my linux is 0.52, but I have no permission to upgrade it.

Also, I tried to re-install the stlearn but same problem occurred.

How can I solve it?? :(

**Comment by duypham2108** [comment]
if you can use anaconda or virtual environment to create an independent environment for python, then you don't need to worry about the permission

**Comment by duypham2108** [comment]
Have you ever tried install numba by anaconda? 
https://anaconda.org/numba/numba

Sorry that we cannot help in this case. I will ask my colleague if there is a solution.

**Comment by anchormok** [comment]
![微信截图_20220316102554](https://user-images.githubusercontent.com/40140273/158504917-a1aac359-5126-4a7e-b553-1e68ebf98f20.png)
As presented in screenshot, I have creat a new environment and conda install the numba 0.55.1 in this environment. When I run st.tl.cci.run, the errors showed that numba in public environment was employed. So when I re-install the stlearn, should I install the numba first?

**Comment by BradBalderson** [comment]
Hi @anchormok 

Could you provide the sequence of steps you use to create the environment & start python?

Looking at the above, my best guess is that when you create the environment the python version is not specified, which results in the global python being used & subsequently alot of global packages. 

To get around this, it would be worth trying creating the environment like this:

`conda create -n stlearn_env python=3.8`

Then activate the environment & install stLearn & try running again. If end-up with numba error again, 
could you try numba v0.53.1; this is the version the CCI was developed with.

**Comment by duypham2108** [comment]
Also make sure when you run:
```
which python
```
It will show the path in your conda env

**Comment by anchormok** [comment]
![微信截图_20220316215204](https://user-images.githubusercontent.com/40140273/158606331-9a90a31c-23ae-4089-b815-785111d7778d.png)
Thanks a lot. According to your precious suggestions, I have confirmed that I specified the version of python, and the path is in the stlearn environment. 
Actually, back to the original error, should we suppose the other reasons instead of the version of numba???

**Comment by BradBalderson** [comment]
Need to confirm numba versioning setup correctly first; we've seen this error with a few different people & in every case was numba version. 

So now we have confirmed the python, can you try:

`import numba`
`print(numba.__version__)`
`print(numba.__path__)`

Above should show two things: 
- numba v0.53.1
- It's installed in your conda env

If we can confirm that, then will look at other possibilities, otherwise numba is still most likely cause.
