### ISSUE TITLE
Installation and requirements of Louvain and leidenalg

### ISSUE THREAD

**Issue by TehseusKunka** [BiomedicalMachineLearning/stLearn#158]
I am using the system of MacOS with M1 MAX (ARM64), when I am install the Stlearn, it comes error with the installation of Louvain package. And I found that the package of Louvain and Leidenalg has no suitable who for macOS-arm64. Is there any solutions?

**Comment by duypham2108** [comment]
You can pre-install louvain or leidenalg first with anaconda. Here is the solution based on scanpy authors:
```
conda install -c conda-forge scanpy python-igraph leidenalg louvain
```
