### ISSUE TITLE
UnsupportedError

### ISSUE THREAD

**Issue by skim245** [BiomedicalMachineLearning/stLearn#162]
Dear Developers, 

I'm trying to run st.tl.cci.run and facing "UnsupportedError" as shown below 

Calculating neighbours...
0 spots with no neighbours, 1 median spot neighbours.
Spot neighbour indices stored in adata.obsm['spot_neighbours'] & adata.obsm['spot_neigh_bcs'].
Altogether 41 valid L-R pairs
Generating backgrounds & testing each LR pair...:   0%|           [ time left: ? ]
---------------------------------------------------------------------------
UnsupportedError                          Traceback (most recent call last)
<ipython-input-17-81bfbce38a26> in <module>
      1 # Running the analysis #
----> 2 st.tl.cci.run(adata, lrs,
      3                   min_spots = 5, #Filter out any LR pairs with no scores for less than min_spots
      4                   distance=0, # None defaults to spot+immediate neighbours; distance=0 for within-spot mode
      5                   n_pairs=100, # Number of random pairs to generate; low as example, recommend ~10,000

~/miniconda3/lib/python3.8/site-packages/stlearn/tools/microenv/cci/analysis.py in run(adata, lrs, min_spots, distance, n_pairs, n_cpus, use_label, adj_method, pval_adj_cutoff, min_expr, save_bg, neg_binom, verbose)
    328     """ Permutation methods generating background per spot, & test lrs in spot.
    329     """
--> 330     perform_spot_testing(
    331         adata,
    332         lr_scores,

~/miniconda3/lib/python3.8/site-packages/stlearn/tools/microenv/cci/permutation.py in perform_spot_testing(adata, lr_scores, lrs, n_pairs, neighbours, het_vals, min_expr, adj_method, pval_adj_cutoff, verbose, save_bg, neg_binom, quantiles)
    100             lr_ = lrs[lr_j]
    101 
--> 102             background, spot_indices = get_lr_bg(
    103                 adata,
    104                 neighbours,

~/miniconda3/lib/python3.8/site-packages/stlearn/tools/microenv/cci/perm_utils.py in get_lr_bg(adata, neighbours, het_vals, min_expr, lr_, lr_score, l_quant, r_quant, genes, candidate_quants, gene_bg_genes, n_genes, n_pairs)
    347     l_, r_ = lr_.split("_")
    348     if l_ not in gene_bg_genes:
--> 349         l_genes = get_similar_genesFAST(
    350             l_quant, n_genes, candidate_quants, genes  # group_l_props,
    351         )

~/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    415         except errors.UnsupportedError as e:
    416             # Something unsupported is present in the user code, add help info
--> 417             error_rewrite(e, 'unsupported_error')
    418         except (errors.NotDefinedError, errors.RedefinedError,
    419                 errors.VerificationError) as e:

~/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    355                 raise e
    356             else:
--> 357                 raise e.with_traceback(None)
    358 
    359         argtypes = []

UnsupportedError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
Unsupported op-code encountered: arrayexpr(expr=(<built-in function sub>, [Var(ref__quants, perm_utils.py:226), Var($cand_quants.509, perm_utils.py:228)]), ty=array(float32, 1d, F))

File "../../../../../miniconda3/lib/python3.8/site-packages/stlearn/tools/microenv/cci/perm_utils.py", line 229:
def get_similar_genesFAST(
    <source elided>
        cand_quants = candidate_quants[:, i]
        abs_diff = ref_quants - cand_quants
        ^

During: lowering "id=7[LoopNest(index_variable = parfor_index.502, range = ($const42.20, $50binary_subscr.24, 1))]{58: <ir.Block at /Users/miniconda3/lib/python3.8/site-packages/stlearn/tools/microenv/cci/perm_utils.py (227)>}Var(parfor_index.502, perm_utils.py:227)" at /Users/miniconda3/lib/python3.8/site-packages/stlearn/tools/microenv/cci/perm_utils.py (227)

Many thanks,

**Comment by BradBalderson** [comment]
Hi Skim,

Best guess is numba version, could you take a look at #157 ?

**Comment by skim245** [comment]
@BradBalderson amazing! 
it solved all the issues :) 
Many thanks !!!
