### ISSUE TITLE
Pseudotime analysis for MERfish

### ISSUE THREAD

**Issue by ShawnXzz** [BiomedicalMachineLearning/stLearn#167]
Hey,

This is a great tool！

I have a question: How can I continue the Spatial trajectory inference analysis after I have processed the MERfish data?

**Comment by duypham2108** [comment]
Thanks for using this. You can start from this step https://stlearn.readthedocs.io/en/latest/tutorials/Pseudo-time-space-tutorial.html#2.-Spatial-trajectory-inference

**Comment by ShawnXzz** [comment]
> 感谢您使用它。您可以从这一步开始https://stlearn.readthedocs.io/en/latest/tutorials/Pseudo-time-space-tutorial.html#2.-Spatial-trajectory-inference
> 
> 注意`eps`参数。对于 MERFISH 数据，您需要将其减少到 5~20
> 
> ```
> st.spatial.trajectory.pseudotime(data,eps=50,use_rep="X_pca",use_label="louvain")
> ```

Hi, Sorry I'm not very familiar with this tool，after I run this step with sample data, I get this error:
`AttributeError: 'NoneType' object has no attribute 'to_adata'`

**Comment by duypham2108** [comment]
You should set the `use_raw = False`

```
data.uns["iroot"] = st.spatial.trajectory.set_root(data,use_label="louvain",cluster=6,use_raw=False)
```

**Comment by ShawnXzz** [comment]
> You should set the `use_raw = False`
> 
> ```
> data.uns["iroot"] = st.spatial.trajectory.set_root(data,use_label="louvain",cluster=6,use_raw=False)
> ```

Thank you very much for the response! I have successfully completed the process.
