### ISSUE TITLE
local spatial trajectory inference

### ISSUE THREAD

**Issue by JuanXie19** [BiomedicalMachineLearning/stLearn#168]
Hi,

I was trying to do spatial trajectory inference at the local level but failed. I couldn't pin  the problem, could you help ?
ps: I was using the same dataset as the tutorial used, and here is the error I got
![image](https://user-images.githubusercontent.com/98572468/169329554-44f3f088-7ad0-41c8-a0b0-a6032b18683b.png)

**Comment by duypham2108** [comment]
I temporarily stopped working this function before. I will try to fix and update soon
