### ISSUE TITLE
arguments order in global level of PSTS method

### ISSUE THREAD

**Issue by JuanXie19** [BiomedicalMachineLearning/stLearn#169]
Hi,
I was running the spatial trajectory inference at the global level following the tutorial. I was curious about the order of clusters in the list_clusters argument: should the order matter?

I tried to switch the order of clusters and it seems that stlearn will give different trajectory order
For instance, 
![image](https://user-images.githubusercontent.com/98572468/169336693-78dd3adc-160d-4425-8566-626facaed951.png)
![image](https://user-images.githubusercontent.com/98572468/169336881-81e68079-150b-45bd-909c-c816ef041557.png)

And if I switch the order,
![image](https://user-images.githubusercontent.com/98572468/169337410-3e122a0e-174a-48e2-ab35-5946837fa34e.png)
![image](https://user-images.githubusercontent.com/98572468/169337517-a247fc2c-fd6b-4ea2-b966-7574bd1ba2f5.png)

Could you tell me how to decide the order of clusters in the list_clusters argument? Or the order shouldn't matter?
Thanks~

**Comment by duypham2108** [comment]
Yes, it should be the same because I ordered it by median of `dpt_pseudotime` value.
Can you please show me this `data.uns["cater_label_index_dict"]` ?

**Comment by JuanXie19** [comment]
> Yes, it should be the same because I ordered it by median of `dpt_pseudotime` value. Can you please show me this `data.uns["cater_label_index_dict"]` ?

Sure, I will paste the content later

**Comment by JuanXie19** [comment]
> Yes, it should be the same because I ordered it by median of `dpt_pseudotime` value. Can you please show me this `data.uns["cater_label_index_dict"]` ?

Hi,
Here is the information you mentioned:
![image](https://user-images.githubusercontent.com/98572468/169438924-fe4aa1ef-10c3-44a8-9a94-822ff752fe5b.png)

And here is the label I used:
![image](https://user-images.githubusercontent.com/98572468/169439024-7f60d165-a270-4551-a81e-be63b4efdac9.png)

**Comment by duypham2108** [comment]
I found the bug. It's because of when I convert from string to integer, it makes the issue.
One way can fix it is that you change the name of clusters to number style ` ["0","1","2","3","4"]` and re-run the method

```
data.cater_label.cat.categories = ["0","1","2","3","4"]
```
I will try to fix the bug and update soon

**Comment by JuanXie19** [comment]
Hi,
Thanks for the reply.

I tried to use number-like labels, but got the following error
![image](https://user-images.githubusercontent.com/98572468/169548061-cda72ae1-bd33-44bf-a2df-07e261c7f788.png)

![image](https://user-images.githubusercontent.com/98572468/169548979-e83cfa87-1848-4a97-b2b0-3c2303ea65a4.png)


if I use integer-typed lael, I got the following error:

![image](https://user-images.githubusercontent.com/98572468/169548565-8324bef5-dd58-4a77-be4c-b6c9e45edffd.png)

![image](https://user-images.githubusercontent.com/98572468/169549190-30464121-5087-4a91-9d21-aa3d76d8b5b3.png)

**Comment by duypham2108** [comment]
I mean list of string like this `["0","1","2","3","4"]` not a list of int. It's still `Categories (5, int64)`, should be `Categories (5, str)`.
If this solution is not working, can you send me your data object through my email. I will try to fix that issue

**Comment by JuanXie19** [comment]
> I mean list of string like this `["0","1","2","3","4"]` not a list of int. It's still `Categories (5, int64)`, should be `Categories (5, str)`. If this solution is not working, can you send me your data object through my email. I will try to fix that issue

Sorry I misunderstood. so should I make the labels string?  

could you provide your email address?

**Comment by duypham2108** [comment]
Yeah, you can use this code too
```
data.cater_label.cat.categories = ["0","1","2","3","4"]
```

My email is duy.pham@uq.edu.au

**Comment by JuanXie19** [comment]
> I mean list of string like this `["0","1","2","3","4"]` not a list of int. It's still `Categories (5, int64)`, should be `Categories (5, str)`. If this solution is not working, can you send me your data object through my email. I will try to fix that issue

Hi,
I just tried the suggested solution (use string typed label) and it perfectly solved the problem ! The order of clusters in the list_clusters() argument didn't affect the results anymore.

Thank you very much!
