### ISSUE TITLE
clusters are not available to construct the spatial trajectory

### ISSUE THREAD

**Issue by JuanXie19** [BiomedicalMachineLearning/stLearn#170]
Hi,

I was running spatial trajectory inference using the example data with my own clustering labels and got the following error:
![image](https://user-images.githubusercontent.com/98572468/170305069-d9935b8f-de59-4d33-b67a-7d7d6c5b31a5.png)

I am not sure what's wrong. When I specify a different cluster pair in the list_clusters argument, it worked; yet for some pairs it threw out this error.

Thanks

**Comment by duypham2108** [comment]
I made a function that checks for the available connection based on the PAGA graph (trajectory inference with gene expression only). You can plot the PAGA by `scanpy.pl.paga` or `st.pl.non_spatial_plot` to see the possible paths. Your cluster 2 and 5 might not be directly connected in the PAGA graph

**Comment by JuanXie19** [comment]
> I made a function that checks for the available connection based on the PAGA graph (trajectory inference with gene expression only). You can plot the PAGA by `scanpy.pl.paga` or `st.pl.non_spatial_plot` to see the possible paths. Your cluster 2 and 5 might not be directly connected in the PAGA graph

Got it, thanks very much for the reply.
