### ISSUE TITLE
question regarding the root and list_clusters

### ISSUE THREAD

**Issue by JuanXie19** [BiomedicalMachineLearning/stLearn#171]
Hi,

I have a question regarding the root and list_clusters. 
In the tutorial, we have the following two lines:

data.uns["iroot"] = st.spatial.trajectory.set_root(data,use_label="louvain",cluster=6,use_raw=True)
st.spatial.trajectory.pseudotimespace_global(data,use_label="louvain",list_clusters=["6","8"])

it first specifies cluster 6 as root, and later it infers the global trajectory between cluster 6 and 8. My question is: do we must include specified root cluster in the list_clusters argument? e.g., is it ok to specify list_clusters=['8','5'], i.e., do not include root cluster in this argument?

Thanks

**Comment by duypham2108** [comment]
You can specify the root in any cluster that not included in the list_clusters

**Comment by JuanXie19** [comment]
> You can specify the root in any cluster that not included in the list_clusters

Thanks very much for the reply.

I noticed another strange thing as follows:
![image](https://user-images.githubusercontent.com/98572468/170545326-5b84b329-57f9-407a-81b7-20fcace5964d.png)

i.e., the clusters involved in the trajectory reported by the tool is different from the one I specified. Is that normal?

**Comment by duypham2108** [comment]
Yes, it's strange. I will need to fix that bug. I think you can set `list_clusters=["4","5"]`. Hope it works.
