### ISSUE TITLE
A question about ‘st.pl.cluster_plot’

### ISSUE THREAD

**Issue by ShawnXzz** [BiomedicalMachineLearning/stLearn#172]
Hi,
I was running the spatial trajectory inference at the global level by using my data. I want to know how to change the corlor or thickness of arrows when I run "st.pl.cluster_plot"?

**Comment by duypham2108** [comment]
I hardcode it in here: https://github.com/BiomedicalMachineLearning/stLearn/blob/ebc9b52f2b4adf7753e264af22ffa9aaa4e175d1/stlearn/plotting/classes.py#L749-L759

 I can put it to the parameters of the `st.pl.cluster_plot` soon. For now, if you are hurry, you can modify the `ClusterPlot` class directly in your local source code and run it again.

**Comment by ShawnXzz** [comment]
> I hardcode it in here:
> 
> https://github.com/BiomedicalMachineLearning/stLearn/blob/ebc9b52f2b4adf7753e264af22ffa9aaa4e175d1/stlearn/plotting/classes.py#L749-L759
> 
> I can put it to the parameters of the `st.pl.cluster_plot` soon. For now, if you are hurry, you can modify the `ClusterPlot` class directly in your local source code and run it again.

Hi，It works！ Thanks very much for your help！
