### ISSUE TITLE
Unable to run trajectory pseudotime analysis on win11

### ISSUE THREAD

**Issue by mvpsc30** [BiomedicalMachineLearning/stLearn#173]
Dear stLearn team,
I was trying to follow the trajectory pseudotime analysis tutorial but I come up with the similar problem as described in #165
I followed you advice and re-install stLearn but the bug is still there.
Here is the error message I got :

C:\PROGRA~3\ANACON~1\envs\stlearn\lib\site-packages\stlearn\spatials\clustering\localization.py:45: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  subclusters = pd.Series()
ValueError: min_samples == 0, must be >= 1.

Could you help me?

Thank you very much!

**Comment by duypham2108** [comment]
I believe the old version still there. Can you uninstall the stlearn first and re-install again?

**Comment by mvpsc30** [comment]
wow! It works! Thx a lot! Wish you a good day!
