### ISSUE TITLE
Spatial deconvolution visualization problem

### ISSUE THREAD

**Issue by LipingChen0607** [BiomedicalMachineLearning/stLearn#174]
Dear developer,
Thank you for sharing this excellent tool! However, when I tried the "spatial deconvolution visualization" part, errors displayed like "KeyError: 'use_quality'".  I have tried to modify the adata.uns["spatial"][library_id] part, but it didn't work, could you give me some advice to deal with this problem? 
Thanks a lot!
<img width="765" alt="截屏2022-06-06 上午10 06 25" src="https://user-images.githubusercontent.com/74603389/172083393-c7936df2-de89-49c3-8893-b55e4bf624b1.png">

**Comment by duypham2108** [comment]
I think your data is not Visium. I recommend you convert your adata and try to plot again with this function 
`adata = st.convert_scanpy(adata)`
Or you can try to read the data again by this tutorial: https://stlearn.readthedocs.io/en/latest/tutorials/Read_any_data.html

**Comment by LipingChen0607** [comment]
Thanks a lot! My problem has been solved.
