### ISSUE TITLE
problem in GO enrichment analysis of LR

### ISSUE THREAD

**Issue by LipingChen0607** [BiomedicalMachineLearning/stLearn#175]
Dear developer,
May I ask a new question again? When I tried to run  the GO enrichment analysis of LR, R library path was unable to determine, and my jupyter kernel restarted every time. I think there may be some mistakes in rpy2 moudlue, but this module could import correctly. Could you give me some advice for solving this problem? Thank you very much!
<img width="936" alt="截屏2022-06-08 上午11 03 56" src="https://user-images.githubusercontent.com/74603389/172523655-f7f3458a-6a8b-47f8-866d-349ee6dee199.png">
<img width="907" alt="截屏2022-06-08 上午11 04 03" src="https://user-images.githubusercontent.com/74603389/172523659-2307bbdb-870a-4321-8df9-f1f1ad247683.png">

**Comment by BradBalderson** [comment]
Hey Liping,

Is R installed at the r_path location? When you run in the terminal:
`/Users/chenliping/miniconda3/bin/R`

Does the R console come up?

If so, other issue may have something to do with running in jupyter notebook. Perhaps trying in the ipython terminal could possibly resolve it. 

Worse case scenario, the GO term analysis here is really just an optional step, so it could be skipped if is too difficult to resolve.
