### ISSUE TITLE
manually combine the images for different array dimensions

### ISSUE THREAD

**Issue by LipingChen0607** [BiomedicalMachineLearning/stLearn#176]
Dear developer,
When I horizontally stacked 2 images using "np.hstack", error occured that input array dimensions for the concatenation axis didn't match exactly. Could you provide some method to adjust the input array dimensions to consistent? Thanks a lot!
<img width="768" alt="截屏2022-06-08 下午6 11 06" src="https://user-images.githubusercontent.com/74603389/172593854-66b53cc8-bd58-48d3-bb80-9904790d53a5.png">

**Comment by LipingChen0607** [comment]
Since I can't stack two images in this way, how could I merge two spatial data in "adata.obsm["spatial"]" in order to plot gene expression? Thank you!

**Comment by duypham2108** [comment]
You can use concatenate from AnnData:

```
adata_concat = adata1.concatenate(adata2)
```

**Comment by LipingChen0607** [comment]
How can I specify the .uns['spatial'] when use plot functions like "st.pl.gene_plot" and "st.pl.lr_plot"? 
Similar to scanpy, I can assign the parameter "library_id" when plot features. 
How to implement it in stlearn? Thanks!
![截屏2022-06-11 上午8 56 51](https://user-images.githubusercontent.com/74603389/173166645-02ecf254-26db-416c-9a93-b905d94b5045.png)
![截屏2022-06-11 上午8 56 37](https://user-images.githubusercontent.com/74603389/173166655-ab2fd77c-7a2b-49cc-8669-325f142e5fe2.png)
![截屏2022-06-11 上午8 57 51](https://user-images.githubusercontent.com/74603389/173166663-3b3258d3-2869-4fa2-9588-b5ae76d0e264.png)
![截屏2022-06-11 上午8 57 43](https://user-images.githubusercontent.com/74603389/173166666-d1863434-826b-4692-bf30-6bde3df02347.png)

**Comment by duypham2108** [comment]
Sorry that we don't support multiple libraries. You can create separate anndata object for this purpose

**Comment by LipingChen0607** [comment]
Okay, thank you!

**Comment by duypham2108** [comment]
@LipingChen0607 Hey, I just added a feature to concatenate multiple spatial transcriptomics data for both image and coordinates data. Currently, it's for visualization purpose only. Hope it help

```
adata_concat = st.concatenate_spatial_adata(adata_list=[adata1,adata2.adata3,adata4], ncols=2)
```

 #180
