### ISSUE TITLE
Some questions about trajectory analysis

### ISSUE THREAD

**Issue by ShawnXzz** [BiomedicalMachineLearning/stLearn#181]
Hi,
I was trying to do spatial trajectory analysis by using my MERFISH data. Now I have some questions about this method:
Q1: After I got the results about  the global level of spatial trajectory inference, the clades in MERFISH data are always so dense that I have a hard time determining which clade to use transition markers detection. Could you give me some advice?
For instanse:
<img width="904" alt="image" src="https://user-images.githubusercontent.com/97502535/176338255-1ada63c3-b22d-47f9-97f4-c67282e45ad4.png">

Q2: I want to improve the visualization by stacking the results of the trajectory analysis with cell boundary images from another analysis software. Could you provide some methods for this?
I want to achieve something like this:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/97502535/176339413-f1595d2e-0261-49c0-b0b7-525cae8b09aa.png">

Thank you very much!

**Comment by duypham2108** [comment]
For the Q1, I recommend you to extract the graph and view it in networkx:
```
from stlearn.utils import _read_graph
import networkx as nx

G = _read_graph(data,"PTS_graph")
remove = [edge for edge in G.edges if 9999 in edge]
G.remove_edges_from(remove)
G.remove_node(9999)
nx.draw_networkx(G)
```
With this code, you can view all the clades. You also can view each clade with a list of nodes:

```
# Set a list of nodes for each clade you want to view in `list_clusters`
st.pl.cluster_plot(data,use_label="sub_cluster_labels",list_clusters=["26","28"],show_trajectories=True)
```

For the Q2, you can extract the graph and set the coordinate for each node and apply to your image. Another way is to replace the H&E image by:

```
st.add.image(adata=data,
             imgpath=IMAGE_PATH,
             library_id="V1_Breast_Cancer_Block_A_Section_1", #(change your library ID here"
             visium=True)
```

**Comment by ShawnXzz** [comment]
> For the Q1, I recommend you to extract the graph and view it in networkx:
> 
> ```
> from stlearn.utils import _read_graph
> import networkx as nx
> 
> G = _read_graph(data,"PTS_graph")
> remove = [edge for edge in G.edges if 9999 in edge]
> G.remove_edges_from(remove)
> G.remove_node(9999)
> nx.draw_networkx(G)
> ```
> 
> With this code, you can view all the clades. You also can view each clade with a list of nodes:
> 
> ```
> # Set a list of nodes for each clade you want to view in `list_clusters`
> st.pl.cluster_plot(data,use_label="sub_cluster_labels",list_clusters=["26","28"],show_trajectories=True)
> ```
> 
> For the Q2, you can extract the graph and set the coordinate for each node and apply to your image. Another way is to replace the H&E image by:
> 
> ```
> st.add.image(adata=data,
>              imgpath=IMAGE_PATH,
>              library_id="V1_Breast_Cancer_Block_A_Section_1", #change your library ID here"
>              visium=True)
> ```

Thanks for your reply!  I have tried for the first question and it works fine. For the Q2, I still don't understand it. If I want to extract the graph and set the coordinate for each node and apply to my image, what information should I extract from my data?

**Comment by duypham2108** [comment]
You can follow this steps. It requires you a bit of coding manually with `networkx`:
- You should use the graph `G` in the Q1
- Extract the clades that you want to visualize
- For each node, you set the image coordinate to it. The coordinates should be matched to the clone in your image
- For draw the trajectory, you can follow this code:
```
# Remember to change the parameters
# https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edges.html
nx.draw_networkx_edges(
                G,
                pos=centroid_dict,
                node_size=self.trajectory_node_size,
                alpha=self.trajectory_alpha,
                width=self.trajectory_width,
                edge_color=self.trajectory_edge_color,
                arrowsize=self.trajectory_arrowsize,
                arrowstyle="-|>",
                connectionstyle="arc3,rad=0.2",
            )
```
