### ISSUE TITLE
cell type specific LR pairs 

### ISSUE THREAD

**Issue by skim245** [BiomedicalMachineLearning/stLearn#182]
Dear authors, 

I came across another question on how to use stLearn to extract information that I and others might be interested in. 

are there any ways to identify or extract LR pairs enriched or downregulated in "cell types" or "condition" or interest? 

thank you in advance!

**Comment by BradBalderson** [comment]
Hi!

For stlearn CCI, we identify LR pairs that facilitate cell type-cell type interactions. 

The results should be in data.uns after running through the `[tutorial](https://stlearn.readthedocs.io/en/latest/tutorials/stLearn-CCI.html)`, print statements after running each function log precisely where the output is stored (think you want data.uns['per_lr_cci_cell_type'], it is a dictionary of LR to dataframes that have counts for number of significantly predict CCI events, you could extract for particular cell types/LRs from here). 

We don't currently support comparing between conditions.
