### ISSUE TITLE
Error in SME clustering

### ISSUE THREAD

**Issue by urowufei** [BiomedicalMachineLearning/stLearn#183]
Dear authors,

I came across an error during SME clustering.
The recommended parameters were used in the SME clustering module. The PCA is done! Kmeans clustering is done! The labels are stored in adata.obs["kmeans"]
LLVM ERROR: Symbol not found: __svml_sqrtf8
Could you please kindly help me to fix this problem.
thank you in advance!

**Comment by duypham2108** [comment]
Can you please try this solution?
https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093

**Comment by urowufei** [comment]
Many thanks. The link gives a perfect answer and solution.
