### ISSUE TITLE
label_transfer_bc.csv

### ISSUE THREAD

**Issue by jinyuanchun** [BiomedicalMachineLearning/stLearn#184]
i practiced use stlearn's Cell-Cell Interaction Analysis, but i can't find `label_transfer_bc.csv` , give me one please

**Comment by duypham2108** [comment]
Please check this file: https://github.com/BiomedicalMachineLearning/stLearn/blob/5e4c966f99ecdfcb568f0b735929163f6cac2a1c/tutorials/label_transfer_bc.csv

We will restore it soon
