### ISSUE TITLE
Qustion about P-value adjustment in Cell-Cell Interaction Analysis

### ISSUE THREAD

**Issue by LipingChen0607** [BiomedicalMachineLearning/stLearn#185]
Dear developer,
I'm confused about the P-value adjustment in Cell-Cell Interaction Analysis.
Could you help me explain what 'correct_axis ' means and how to set this parameter in different conditions?
I have run Cell-Cell Interaction Analysis based on 'correct_axis'=None/spot/LR, and the data.uns['lr_summary'] in these three results seems different.
Could you tell me the meaning of 'n_spots_sig_pval' in data.uns['lr_summary']?
Thank you very much!
<img width="497" alt="截屏2022-08-22 上午10 46 42" src="https://user-images.githubusercontent.com/74603389/185830414-6374d71b-ff5a-45ff-a287-783198ba5781.png">

**Comment by BradBalderson** [comment]
Hi Liping,

Sorry for the late reply! 

You can find a description of the parameters here: https://stlearn.readthedocs.io/en/latest/stlearn.tl.cci.adj_pvals.html#stlearn.tl.cci.adj_pvals

Just copy-pasting for convenience:

**correct_axis** (str) – Either ‘spot’, ‘LR’, or None; former corrects for number of LRs tested in each spot, middle corrects for number of spots tested per LR, and latter performs no adjustment (uses p-value for significant testing)

It's because we are testing for enrichment of a LR per spot neighbourhood. So can either correct for number of LRs which we are testing in a spot, or for the number of spots tested per LR, or we can perform no p-value correction.

Think this downstream diagnostic will help make the decision:
`st.pl.lr_diagnostics(data, figsize=(10,2.5))`
![image](https://user-images.githubusercontent.com/24308582/186530285-3e4e3f02-9867-45cd-a959-ef49bcb537f1.png)

Whichever of these reduces the bias toward more highly and/or more frequently expressed LRs is your best choice.

This is an analysis decision that will depend on your data. 

Thanks alot for the question! Hopefully helps others too.

Let me know if unclear :)

**Comment by LipingChen0607** [comment]
Thanks for your detailed answer! I got it :)

I have two more questions to ask.

1. When I have calculated the sig spot of LRs, how could I get these spots' barcode information for further analysis?

2. I have five different groups of samples for cell-cell interaction analysis. And I want to compare the LR levels in different groups. How could I compare the same LRs level in different groups more accurately? 

Since the total number of spots in different samples is different, I think it may be inaccurate to just compare the number of sig spots between different samples. But when using (number of sig spots/ total spots) to compare, the results seem to conform with the biological common sense. Is there any other better comparison method?

Thank you!

**Comment by BradBalderson** [comment]
Awesome, glad I could help :) 

1. You can find a matrix in data.obsm['lr_sig_scores'] of shape n_spots by n_LRs. Positive values in this matrix indicate significance of the LR in the respective spot (non-significant spots are set to zero). The LRs on the columns are the same as the index in data.uns['lr_summary'] (sorry not the best way of structuring this data, hindsight is 20-20, though).

2. In the group we are exploring comparing between samples as the next step in the analysis. Currently, I can think of two options which could be easy to implement, but would require alot of work to check to make sure they work well:
      a) If have just two samples: A Fisher's exact test on the significant spots between studies, structuring the contingency matrix such that each row; sig spots, non-sig spots, and each column; sample 1 and sample 2. Clearly this is an issue if have more than two samples.
     b) If have multiple samples between conditions; perhaps another approach could be to use compositional data analysis (CoDa, Tom Quinn has alot of good papers/reviews on this, e.g. [review](https://academic.oup.com/bioinformatics/article/34/16/2870/4956011)) on the ratios, (number of sig spots/ total spots), for each sample. You can transform the ratios from Atchison geomety to euclidean geometry using the centred-log-ratio (clr) transformation (available in scikit-bio http://scikit-bio.org/docs/0.4.2/generated/skbio.stats.composition.html) and perform independent Welch's t-test using scipy on the clrs between conditions, or other statistical tests (e.g. ANOVA). I've used this before to call differential abundance of cell types in scRNA-seq data, for full details see the Methods section **Differential abundance analysis and doublet detection** in this [paper](https://journals.biologists.com/dev/article/149/5/dev200076/274592/Selective-requirement-for-polycomb-repressor).
     c) Perhaps another option is to take LR scores including for spots which are non-significant, & do a differential expression between samples in each group. I think this will get a little tricky to try and normalise between the samples and there will be issues with pseudoreplication if treat each spot as an independent sample, so this one I'm the least confident in. 

These are just a few educated guesses, have not tested any of these, so not sure how well they will work.

**Comment by LipingChen0607** [comment]
Thank you for your patient reply! I will try these methods to compare.

I still can't find the spot_sig barcode in data.obsm['lr_sig_scores'], could you point out my mistake?
And I wonder how could I save data.obsm as a csv file for detail analysis.
<img width="694" alt="截屏2022-08-25 下午1 04 21" src="https://user-images.githubusercontent.com/74603389/186580671-ec3c6886-4ca3-4c98-9bc2-137825eb3768.png">
<img width="737" alt="截屏2022-08-25 下午1 04 45" src="https://user-images.githubusercontent.com/74603389/186580680-159c8876-a036-4e4c-b2e7-e2eaf32f862f.png">

Thanks a lot!

**Comment by BradBalderson** [comment]
Sorry, should have mentioned the rows of data.obsm['lr_sig_scores'] are the same as data.obs_names. 

You can convert data.obsm['lr_sig_scores'] to a pandas dataframe & save as below:
```
   import pandas as pd

   lr_sig_df = pd.DataFrame(data.obsm['lr_sig_scores'], index=data.obs_names.values, 
                                                columns=data.uns['lr_summary'].index.values)

   lr_sig_df.to_csv('lr_sig_scores.txt', sep='\t')
```

To get the barcodes per LR, could use:
```
   import numpy as np

   lr_sig_scores = data.obsm['lr_sig_scores']

   lr_sig_barcodes = {}
   for i, lr in enumerate(data.uns['lr_summary'].index):
      lr_scores = lr_sig_scores[:, i]
      sig_indices = np.where(lr_scores > 0)[0]
      sig_barcodes = data.obs_names.values[sig_indices]
      
      lr_sig_barcodes[lr] = sig_barcodes
```

Apologies for cryptic data structure, hopefully the above is what you're after. I haven't tested it, so may need a little tweaking, but should be in the ball-park. 

Thanks for persevering :)

**Comment by LipingChen0607** [comment]
I'm sorry that my Python level is limited. When I try the second code above, there will be a lot of spot barcodes, which is not the right lr_sig_barcodes. I don't know what is wrong and want to ask you for help again. Thank you!
<img width="519" alt="截屏2022-08-25 下午7 25 54" src="https://user-images.githubusercontent.com/74603389/186652293-f1e88cc6-5328-453b-a110-dff37f7e9587.png">

**Comment by jinyuanchun** [comment]
> i chech my data.obsm['lr_sig_scores'], found negative values.  what does the means?

**Comment by BradBalderson** [comment]
@LipingChen0607, i is the index, lr is the name of the ligand-receptor. To get barcode for the particular LR you set as i, would be something like:

`
lr = 'Angpt2_Tek'
i = np.where(LR_data_INF.obsm['lr_summary'].index.values)[0][0]
lr_scores = lr_sig_scores[:, i]
sig_indices = np.where(lr_scores > 0)[0]
sig_barcodes = LR_data_INF.obs_names.values[sig_indices]
`

**Comment by BradBalderson** [comment]
@jinyuanchun if provided log-cpm in data.X, it should not be negative. I'm guessing you might have scaled the data beforehand? Recommend not doing this. Just log1p as input.
