### ISSUE TITLE
how can i understand stlearn.create_stlearn() Parameters : scale 

### ISSUE THREAD

**Issue by jinyuanchun** [BiomedicalMachineLearning/stLearn#186]
I have raw datas : exp_matrix.csv, spatial.csv, annotation.csv
I  use api ： stlearn.create_stlearn() ，but I do not understand the ”scale“ Parameters . 
how to set it ?

**Comment by duypham2108** [comment]
If you don't have the image (H&E or any type of background image) then you don't need to set it (default = None). The purpose of `scale` parameter is to reduce the size of the image

**Comment by jinyuanchun** [comment]
thank u

**Comment by jinyuanchun** [comment]
thank u
