### ISSUE TITLE
question about CCI

### ISSUE THREAD

**Issue by jinyuanchun** [BiomedicalMachineLearning/stLearn#188]
Thank you for developing such a great package. Well, I have one small question about "stLearn Cell-Cell Interaction Analysis". i have finished st.tl.cci.run() and st.tl.cci.run_cci(). acording to your paper, how can i  get
1  L-R data like fig. b, 
2 diversity score(represent cell type diversity) lik fig. e 
3 cci_score(fig f) represent , merged data  used by L-R cluster with highest L-R activities (as shown in b)  cell type heterogeneity (as shown in e) 
![image](https://user-images.githubusercontent.com/40689145/190037792-e48a7252-39ae-4bfa-b860-98d1cfcf5028.png)

**Comment by BradBalderson** [comment]
1. Haven't implemented, but can generate using the significant LR score information outputted. Please read the documentation here, there is significant detail provided about output format: https://stlearn.readthedocs.io/en/latest/stlearn.tl.cci.run.html#stlearn.tl.cci.run
2-3. There have been significant updates to scoring process, new paper to be released soon. But the LR scores are found as detailed in the above documentation. Think I also wrote some additional information in other thread #185

**Comment by jinyuanchun** [comment]
3q

**Comment by BradBalderson** [comment]
Sorry I don't think I understand what you mean by '3q'

**Comment by jinyuanchun** [comment]
sorry, i mean "thank you"

**Comment by BradBalderson** [comment]
haha okay, I was thinking it might be that since it sounds like it, but had never seen it before so just thought I'd check :) 

No worries!
