### ISSUE TITLE
data read in error

### ISSUE THREAD

**Issue by jk86754** [BiomedicalMachineLearning/stLearn#189]
Hi,

Can you please help me figure out what is going wrong here?

![image](https://user-images.githubusercontent.com/11413558/191117012-b927b9a2-63c3-4bbe-ab25-3c9436057365.png)

Visium V2

Thanks!

**Comment by duypham2108** [comment]
Is your `datadir` contains the standard Visium folder?
If it's right, can you check the `scalefactors_json.json`. It should be look something like this:
```
{"spot_diameter_fullres": 177.4829519178534, "tissue_hires_scalef": 0.08250825, "fiducial_diameter_fullres": 286.7032300211478, "tissue_lowres_scalef": 0.024752475}
```

**Comment by jk86754** [comment]
Yes, as far as i can tell, it contains the standard files.
![image](https://user-images.githubusercontent.com/11413558/191187541-fd4752ac-b3c9-4f17-a682-633b1f06a6ff.png)

The 'spatial' folder:
![image](https://user-images.githubusercontent.com/11413558/191187630-96450cdb-465c-4983-ae96-ec9169774640.png)

The scalefactors_json.json file:
{"tissue_hires_scalef": 0.11464603, "tissue_lowres_scalef": 0.03439381, "fiducial_diameter_fullres": 210.2140465231902, "spot_diameter_fullres": 130.13250499054632}

Looks like the order of parameters in my json file is different from yours; not sure if this matters.

**Comment by jk86754** [comment]
Tried reading in the data with a modified json file but i am still getting the same error.

**Comment by duypham2108** [comment]
Can you try this code and show me the printed scale?

```
import stlearn as st
import scanpy as sc
data = sc.read_visium(data_dir)

library_id = list(data.uns["spatial"].keys())[0]
scale = data.uns["spatial"][library_id]["scalefactors"][
            "tissue_" + quality + "_scalef"
        ]
print(scale)
```

**Comment by jk86754** [comment]
I get the error below.
![image](https://user-images.githubusercontent.com/11413558/191213034-0095f483-3ddc-4020-b39e-2c98a7ab1937.png)

**Comment by duypham2108** [comment]
I updated the comment, please try again

**Comment by jk86754** [comment]
Thanks.

![image](https://user-images.githubusercontent.com/11413558/191215289-5245aeb2-cf20-47dc-9385-6caa65b5f755.png)

**Comment by duypham2108** [comment]
It seems work well with the reading part. The convert part may have problem.
Can you try this code:

```
data= st.convert_scanpy(data)
```

If it's not working, please print the data and show me.

**Comment by jk86754** [comment]
This indeed reproduces the first error.
![image](https://user-images.githubusercontent.com/11413558/191247090-24088505-5814-45ea-b300-43d3ed2241e7.png)

**Comment by jk86754** [comment]
![image](https://user-images.githubusercontent.com/11413558/191247244-89f80f72-7058-433f-b4fb-1848e318ff7a.png)

**Comment by duypham2108** [comment]
You can try following solutions:
- Solution 1:
```
import numpy as np
data.obsm["spatial"] = np.array(data.obsm["spatial"] )
```
- Solution 2:
```
scale = data.uns["spatial"][library_id]["scalefactors"][
            "tissue_" + quality + "_scalef"
        ]
data.uns["spatial"][library_id]["scalefactors"]["tissue_hires_scalef"] = float(scale)
```

Then run the `convert_scanpy` like above
if it's not working, please show the `data.obsm["spatial"]`

**Comment by jk86754** [comment]
I tried both, same error.
![image](https://user-images.githubusercontent.com/11413558/191256429-c9957b4d-790c-4f9a-8b18-b2e2c61885f5.png)

**Comment by jk86754** [comment]
Thank you. This seems to have solved the problem.

![image](https://user-images.githubusercontent.com/11413558/191257738-6a891688-4cdc-4e79-b81e-84c3c2253c3c.png)
