### ISSUE TITLE
cell type specific LR pairs like #182

### ISSUE THREAD

**Issue by jinyuanchun** [BiomedicalMachineLearning/stLearn#194]
thank u for your greate  package for CCI analysis. i am intersting about the question like # 182
1 how can i understand the data structure --data.uns['per_lr_cci_cell_type']. row is sender cells ? columns is recepter cells? and  number is spots/cell number?
![image](https://user-images.githubusercontent.com/40689145/192235898-a897e184-8030-441f-9e87-2d65f7dbeecf.png)
2 how can i get the spot/cell's  coordinate?

**Comment by BradBalderson** [comment]
Hi @jinyuanchun,

1) Your interpretation is correct, this is the number of interacting spots/cells between those cell types via the respect LR pair.
2) Actually there is some example code/explanation you kind find the thread of #185 to get significant barcodes for the spots.

**Comment by jinyuanchun** [comment]
hi ,thank you for you answer, i thindk i make question 2  unclear. 
base on 1, for example ,from the sender vascular to receptor  Lymphoid ,there is 94 spots by A2M_LRP1, how can i get the spots's ID?

**Comment by BradBalderson** [comment]
Hi @jinyuanchun, there is example code at the bottom of this thread: #185 

I'll copy-paste here so it's clear:
```
lr = 'Angpt2_Tek'
# Just converting to a df here to make it clear what the rows/columns are since is array.
lr_sig_df = pd.DataFrame(data.obsm['lr_sig_scores'], index=data.obs_names.values, 
                                                columns=data.uns['lr_summary'].index.values)
lr_sig_scores = lr_sig_df.values

i = np.where(data.obsm['lr_summary'].index.values==)[0][0]
lr_scores = lr_sig_scores[:, i]
sig_indices = np.where(lr_scores > 0)[0]
sig_barcodes = data.obs_names.values[sig_indices]
```

**Comment by BradBalderson** [comment]
So you mean the significant barcodes corresponding those particular interacting cell types? 

i.e. barcodes for Myeloid and Vascular cells interacting via A2M_LRP1?

**Comment by jinyuanchun** [comment]
yes

**Comment by BradBalderson** [comment]
I see, have implemented that internally in stLearn but it's an intermediate calculation for getting the interaction matrix, but also for adding the interaction arrows to the spatial plot. 

It would take a little time for me to figure out how to do it, but in the meantime I would suggest looking at the 'add_arrows' function in https://github.com/BiomedicalMachineLearning/stLearn/blob/master/stlearn/plotting/cci_plot_helpers.py.

This code segment is a good starting point:
```
    L_bool = l_expr > min_expr
    R_bool = r_expr > min_expr

    # Getting the edges, from sig-L->R and sig-R<-L #
    forward_edges, reverse_edges = get_edges(adata, L_bool, R_bool, sig_bool)

    # If int_df specified, means need to subset to CCIs which are significant #
    if type(int_df) != type(None):
        spot_bcs = adata.obs_names.values.astype(str)
        spot_labels = adata.obs[use_label].values.astype(str)
        label_set = int_df.index.values.astype(str)
        interact_bool = int_df.values > 0

        # Subsetting to only significant CCI #
        edges_sub = [[], []]  # forward, reverse
        # ints_2 = np.zeros(int_df.shape) # Just for debugging make sure edge
        # list re-capitulates edge-counts.
        for i, edges in enumerate([forward_edges, reverse_edges]):
            for j, edge in enumerate(edges):
                k_ = [0, 1] if i == 0 else [1, 0]
                celltype0 = np.where(label_set == spot_labels[spot_bcs == edge[k_[0]]])[
                    0
                ][0]
                celltype1 = np.where(label_set == spot_labels[spot_bcs == edge[k_[1]]])[
                    0
                ][0]
                celltypes = np.array([celltype0, celltype1])
                # For debugging purposes, used to find indexing bug #
                # print(label_set[celltypes[k_[0]]],
                #       label_set[celltypes[k_[1]]])
                # print( celltypes[k_[0]], celltypes[k_[1]] )
                # print( interact_bool[celltypes[k_[0]], celltypes[k_[1]]] )
                if interact_bool[celltypes[k_[0]], celltypes[k_[1]]]:
                    edges_sub[i].append(edge)
```

The get_edges function there is getting edges of significant interacting cells/spots, then subsetting to those edges that have cell types which are over-represented in interacting for a particular LR pair. 

Should be possible to edit this such that you get edges/barcodes which are specific to two given cell types

**Comment by jinyuanchun** [comment]
thank you for your detailed answers,I will seriously study the code you provide
