### ISSUE TITLE
 Visualizing cci results with Stereo_seq 

### ISSUE THREAD

**Issue by Madong1110** [BiomedicalMachineLearning/stLearn#195]
I was trying to apply stlearn cci in datas from Stereo_seq.found issues that cci results cannot be visualized,because data strcuture of object ['spatial'] exists different between 10X visum and BGI Stereo_seq .
Stereo_seq
![image](https://user-images.githubusercontent.com/109155205/192424228-75e4e541-dcb3-4929-b668-ec88590c355e.png)
10X visum
![image](https://user-images.githubusercontent.com/109155205/192424156-1e180b9a-1461-4db7-be2c-b9e1f1c1b2ab.png)
ERROR
![image](https://user-images.githubusercontent.com/109155205/192424397-620e830d-3fa3-4d24-b21f-8b557e4d6357.png)
 How can i figure out this problem, Thank you!

**Comment by duypham2108** [comment]
Can you try this tutorial to read the Stereo_seq: https://stlearn.readthedocs.io/en/latest/tutorials/Read_any_data.html

**Comment by Madong1110** [comment]
> Can you try this tutorial to read the Stereo_seq: https://stlearn.readthedocs.io/en/latest/tutorials/Read_any_data.html

Thank you for your  reply!  it work well following your above  tutorial. Thank a lot!
