### ISSUE TITLE
stlearn.pl.deconvolution_plot's results without legend

### ISSUE THREAD

**Issue by ZgtL15** [BiomedicalMachineLearning/stLearn#196]
Hi, i am using your excellent package for my research. 
now, i am trying to use the "stlearn.pl.deconvolution_plot" to generate the deconvolution result. But the result doesn't have the legend,  How can i figure out this problem, Thank you!
![image](https://user-images.githubusercontent.com/74951994/192499694-e9dc1ccb-602e-4de9-b6a1-1305a7ef275b.png)
![image](https://user-images.githubusercontent.com/74951994/192499819-f0dfe0d8-80ea-4c42-a34d-686ad2b4810f.png)
![image](https://user-images.githubusercontent.com/74951994/192499756-e0aa6bfa-260a-4157-a188-e223e7cb66d0.png)

**Comment by duypham2108** [comment]
We fixed in the github version. Please uninstall the old version by `pip uninstall stlearn` and clone the github and install with this code:
```
git clone https://github.com/BiomedicalMachineLearning/stLearn.git
cd stlearn
python setup.py install
```

**Comment by ZgtL15** [comment]
After reinstalling, our problem was solved.Thank you for your reply.
