### ISSUE TITLE
some questions about transition markers detection

### ISSUE THREAD

**Issue by ShawnXzz** [BiomedicalMachineLearning/stLearn#200]
Hi@duypham2108！
I am doing trajectory analysis. I'm wondering why I'm getting different results from my transition markers detection in the same clade? My code is shown in the image below, it is the same both times.
`st.spatial.trajectory.detect_transition_markers_clades(adata,clade=2703,use_raw_count=False,cutoff_spearman=0.01)
adata.uns['clade_9874'] = adata.uns['clade_9874'][adata.uns['clade_9874']['gene'].map(lambda x: "RPL"  not in x)]
adata.uns['clade_9874'] = adata.uns['clade_9874'][adata.uns['clade_9874']['gene'].map(lambda x: "RPS" not in x)]
st.pl.trajectory.transition_markers_plot(adata,top_genes=30,trajectory="clade_9874")`

<img width="305" alt="Myeloids_clade" src="https://user-images.githubusercontent.com/97502535/196014002-2749d358-8b57-47e5-8dc1-019a18b4827e.png">
<img width="708" alt="image" src="https://user-images.githubusercontent.com/97502535/196014132-f3b9656f-9c61-4221-8f6d-f16b688c9358.png">

**Comment by duypham2108** [comment]
At first, you run for the clade 2703 but visualize the clade 9874. Let me run the test again and back to you later.

Also, I think there are too many sub-clusters. Just not sure about the dataset. `st.spatial.trajectory.pseudotime(data,eps=50,use_rep="X_pca",use_label="louvain")`. You may change `eps` parameter to more than 50 (depend on the pixel distance).

**Comment by ShawnXzz** [comment]
> You may change `eps` parameter to more than 50 (depend on the pixel distance).

I'm sorry my code is a little buggy, but I do clade9874 at runtime. Also, my data is similar to MERFISH data, so the original parameter used was "eps=25" as you suggested, but I set it to 50 due to too many sub-clusters. Now I'm more wondering, how can I reproduce the previous results? This is very important to me. thank you.

**Comment by duypham2108** [comment]
I run the test with the same way of your code block. I got similar result after run it two times. I want to confirm that you mean you run two time of these code or the whole analysis?

**Comment by ShawnXzz** [comment]
> I run the test with the same way of your code block. I got similar result after run it two times. I want to confirm that you mean you run two time of these code or the whole analysis?

I ran the full analysis twice.

**Comment by duypham2108** [comment]
Can you check the code again for the parameter `random_state` in some functions like PCA or clustering which is affected by random effect?
