### ISSUE TITLE
PSTS with Xenium data 

### ISSUE THREAD

**Issue by duypham2108** [BiomedicalMachineLearning/stLearn#203]
Modify functions to work with large spatial transcriptomics data
- [x] Fixed the speed performance of PSTS
- [x] Change the `tree_plot`
- [x] Fixed some small bugs

(I will update more later)
![image](https://user-images.githubusercontent.com/25328074/197111157-b020e035-d5ec-4e05-ba5c-f4e867667b9e.png)

**Comment by duypham2108** [comment]
@sooheelee

**Comment by duypham2108** [comment]
- [x] Added ReadXenium
- [x] Fixed `cluster_plot` speed performance
- [ ]  Add zoom specific region feature
#204

**Comment by jefferyUstc** [comment]
Hi, Under what circumstances, the result of tree_plot is blank?

**Comment by duypham2108** [comment]
> Hi, Under what circumstances, the result of tree_plot is blank?

Is it a blank white plot or does not show anything?
Please add this before the plot of it does not show anything, add this line before the plotting function

```
%matplotlib inline
```

**Comment by jefferyUstc** [comment]
Hi, Thank you for your reply. I tried this, but it doesn't work.

The error seems to start from here： 
```
st.pl.cluster_plot(adata, use_label="LABEL", show_trajectories=True,
                   list_clusters=["A", "B", "C"], show_subcluster=True)
```
This function outputs the right image without trajectories, though `show_trajectories=True` (sorry for that i cannot post the resulting image in this issue, for potential security problem.)

However, when i tried the following codes:
```
import networkx as nx
from anndata import AnnData
from typing import Optional

def _read_graph(adata: AnnData, graph_type: Optional[str]):

    if graph_type == "PTS_graph":
        graph = nx.from_scipy_sparse_array(
            adata.uns[graph_type]["graph"], create_using=nx.DiGraph
        )
    else:
        graph = nx.from_scipy_sparse_array(adata.uns[graph_type]["graph"])
    node_dict = adata.uns[graph_type]["node_dict"]
    node_dict = {int(k): int(v) for k, v in node_dict.items()}

    relabel_graph = nx.relabel_nodes(graph, node_dict)

    return relabel_graph
G = _read_graph(adata, "PTS_graph")

remove = [edge for edge in G.edges if 9999 in edge]
G.remove_edges_from(remove)
G.remove_node(9999)

centroid_dict = adata.uns["centroid_dict"]
centroid_dict = {int(key): centroid_dict[key] for key in centroid_dict}

_ = nx.draw_networkx_edges(
                G,
                pos=centroid_dict,
                arrowstyle="<|-",
                connectionstyle="arc3,rad=0.2"
            )
```

It seems to generate the right result:
<img width="418" alt="image" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/44384930/c0ab1ef2-e4a7-4297-9378-9fa7d27bd7df">

**Comment by jefferyUstc** [comment]
> > Hi, Under what circumstances, the result of tree_plot is blank?
> 
> Is it a blank white plot or does not show anything? Please add this before the plot of it does not show anything, add this line before the plotting function
> 
> ```
> %matplotlib inline
> ```
blank white plot

**Comment by duypham2108** [comment]
It might be the problem of the cluster name. Due to the old design, we can only use the number-like label. Please try to change the current `LABEL` to numbers like "0", "1", "2" rather than "A", "B", "C". I can give an example here:

```
# A list equal to the length of the original LABEL clusters
adata.obs.LABEL.cat.categories = ["0","1","2"]
```
