### ISSUE TITLE
Where is the input data in CCI manual?

### ISSUE THREAD

**Issue by Feng-Zhang** [BiomedicalMachineLearning/stLearn#206]
Thanks for developing the great package. I'm running [the CCI manual](https://stlearn.readthedocs.io/en/latest/tutorials/stLearn-CCI.html). The code is below:
```
# Loading raw data #
data = st.Read10X(data_dir)
data.var_names_make_unique()
st.add.image(adata=data,
             imgpath=data_dir+"spatial/tissue_hires_nobg.png",
             library_id="V1_Breast_Cancer_Block_A_Section_1", visium=True)

# Basic normalisation #
st.pp.filter_genes(data, min_cells=3)
st.pp.normalize_total(data) # NOTE: no log1p
# Adding the label transfer results,  #
spot_mixtures = pd.read_csv(data_dir+'../../Brad/label_transfer_bc.csv', index_col=0, sep='\t')
```
I guess that the h5 and spatial file you used is from [here](https://www.10xgenomics.com/resources/datasets/human-breast-cancer-block-a-section-1-1-standard-1-0-0), is it?
However, I don't find the input files of "tissue_hires_nobg.png" and "label_transfer_bc.csv".
Thank you in advance.

**Comment by duypham2108** [comment]
The png file is not important to run the analysis. For the label transfer file, you can find it here:
https://github.com/BiomedicalMachineLearning/stLearn/tree/master/resource

**Comment by Feng-Zhang** [comment]
Thank you. It works.
