### ISSUE TITLE
Problem with st.tl.cci.run_cci()

### ISSUE THREAD

**Issue by xfchen0912** [BiomedicalMachineLearning/stLearn#214]
Hello, Thank you for the useful package!
I‘m doing **Cell-Cell Interaction Analysis** follow the tutorals step by step , when I use `st.tl.cci.run_cci()`, the following error occurred
<img width="1709" alt="image" src="https://user-images.githubusercontent.com/92902438/203592610-ece8f9c4-0c41-4066-bba8-d0ff8a9a479a.png">
Looking forward to your reply！

**Comment by Hui-Se** [comment]
I also encountered this error. And I search it in source code and find that stlearn/tools/microenv/cci/het_helpers.py file line 224 return 4 variables while run_cci function can only receive 2 vars.

**Comment by xfchen0912** [comment]
> I also encountered this error. And I search it in source code and find that stlearn/tools/microenv/cci/het_helpers.py file line 224 return 4 variables while run_cci function can only receive 2 vars.

Did you solve this problem?

**Comment by xfchen0912** [comment]
> I also encountered this error. And I search it in source code and find that stlearn/tools/microenv/cci/het_helpers.py file line 224 return 4 variables while run_cci function can only receive 2 vars.
Hi @Hui-Se 
Did you solve this problem?

**Comment by duypham2108** [comment]
@Hui-Se @xfchen0912 
Thanks for pointing it out.
We did a hot fix. You can install the master branch version. We will soon update to the version 4.0.11 in pip

**Comment by Hui-Se** [comment]
> > I also encountered this error. And I search it in source code and find that stlearn/tools/microenv/cci/het_helpers.py file line 224 return 4 variables while run_cci function can only receive 2 vars.
> 
> Hi @Hui-Se Did you solve this problem?
@xfchen0912 

I  briefly use **insepect** module to modify source code and execute it like this.
`import inspect

source = inspect.getsource(st.tl.cci)
new_source = source.replace('spot_bcs, cell_data = get_data_for_counting(adata, use_label, mix_mode, all_set)', 'spot_bcs, cell_data = get_data_for_counting(adata, use_label, mix_mode, all_set)[:2]')
exec(new_source, st.tl.cci.__dict__)`
And then I re-run function `run_cci` and it works.

**Comment by xfchen0912** [comment]
I get it, thank you both !

**Comment by duypham2108** [comment]
It should work on the master branch now. We will test it again and update a new version tomorrow
