### ISSUE TITLE
st.pl.trajectory.tree_plot not show cropped image for each node

### ISSUE THREAD

**Issue by xiaojjia** [BiomedicalMachineLearning/stLearn#216]
Hello, thanks for your useful packages!
In the result of 'st.pl.trajectory.tree_plot(data)' with stlearn 0.4.10 version, the plot dont show cropped images for each node, just as follows. then, I added 'show_all = True', and it still doesnt work.
could u give me some suggestions? looking forward to your reply!
![image](https://user-images.githubusercontent.com/102225308/203885670-148f5eb7-4a02-4f89-8676-5697e42e7659.png)
![image](https://user-images.githubusercontent.com/102225308/203885720-70639b7e-7db0-4c27-8d69-2f18f4efd117.png)

**Comment by duypham2108** [comment]
We removed this cropped functions due to the issue of large number of nodes in the new version.
You can downgrade to the version `0.4.8` or using `st.pl.cluster_plot` and use `zoom_coord` to cropped each of the sub-cluster
For example:

```
st.pl.cluster_plot(adata,use_label="louvain", size=10,
                   zoom_coord=[4000,4400,4700,5100],
                   show_color_bar=False)
```

**Comment by xiaojjia** [comment]
> We removed this cropped functions due to the issue of large number of nodes in the new version. You can downgrade to the version `0.4.8` or using `st.pl.cluster_plot` and use `zoom_coord` to cropped each of the sub-cluster For example:
> 
> ```
> st.pl.cluster_plot(adata,use_label="louvain", size=10,
>                    zoom_coord=[4000,4400,4700,5100],
>                    show_color_bar=False)
> ```

yeah, the version `0.4.8`  worked well, and `st.pl.cluster_plot` also can do it but a bit complicated. Thanks a lot!
