### ISSUE TITLE
How to show figure in python console 

### ISSUE THREAD

**Issue by Feng-Zhang** [BiomedicalMachineLearning/stLearn#218]
Dear authors, 
I am running the code given from [the maunal](https://stlearn.readthedocs.io/en/latest/tutorials/stSME_clustering.html).
```
# K-means clustering on stSME normalised PCA
st.tl.clustering.kmeans(data_SME,n_clusters=19, use_data="X_pca", key_added="X_pca_kmeans")
st.pl.cluster_plot(data_SME, use_label="X_pca_kmeans")
```
The above code expects plotting a figure, but not in python console when I debug the code using pycharm. However, the figure shows up when I use notebook. 
This seems that I have to use like `plt.show()` function to show it. But `plt.show()`  doesn't work in this case. 
Could you give me a hand? 
Thank you.

**Comment by duypham2108** [comment]
Can you try this code to use `figure` to show it
```
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
st.pl.cluster_plot(data_SME, use_label="X_pca_kmeans", ax=ax)
fig.show()
```

**Comment by Feng-Zhang** [comment]
Sorry for my bad. 
`plt.show()` works.
