### ISSUE TITLE
Fail to read Space Ranger output file with stlearn.Read10X.

### ISSUE THREAD

**Issue by jingwyang** [BiomedicalMachineLearning/stLearn#220]
Hi there.
I used _stLearn_ package to read the output files of Space Ranger but failed with the error "TypeError: can't multiply sequence by non-int of type 'float'.
I used the latest version of _stLearn_ (0.4.11) and have no idea with this problem. Could you kindly give me some suggestion. Thanks!
The input path as well as the error report are listed following
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/29428150/213363526-86a50ab6-e596-4f28-8ac2-2b0478fe86ef.png">

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/29428150/213362656-e7778ae0-9d0e-4139-94e6-28e6005e32e5.png">

**Comment by duypham2108** [comment]
We fixed it in the github version and will publish it soon.
Can you please uninstall the current version, clone this repo and install?

Here is the bash script you can use:
```
pip uninstall stlearn --yes
git clone https://github.com/BiomedicalMachineLearning/stLearn.git
cd stLearn
python setup.py install
```

**Comment by jingwyang** [comment]
Thanks very much. This works!
