### ISSUE TITLE
papers cited stlearn method

### ISSUE THREAD

**Issue by LipingChen0607** [BiomedicalMachineLearning/stLearn#221]
Could you please provide some papers analyzing cell-cell interaction in spatial transcriptome data using stLearn? Thanks a lot!

**Comment by duypham2108** [comment]
I found some papers that cited stLearn and mentioned the cell-cell interaction part here:
- https://www.mdpi.com/2072-6694/15/1/164
- https://www.sciencedirect.com/science/article/pii/S1550413122005009

**Comment by LipingChen0607** [comment]
Thank you very much!
