### ISSUE TITLE
Can stLearn analyze the SpaceRanger2 data based on CytAssist-Visium FFPE ?

### ISSUE THREAD

**Issue by tyaoi** [BiomedicalMachineLearning/stLearn#227]
Hi,

I wonder whether stLearn can analyze the  SpaceRanger 2 processed data obtained with CytAssist-Visium FFPE .

tyaoi

**Comment by duypham2108** [comment]
Sure you can. It can also be read by st.Read10X function and all other functions will work

**Comment by tyaoi** [comment]
Hi, duypham2108!

The first time it did not work properly was due to an elementary mistake of putting the pre-extracted Vissium data file (.gz) and the post-extracted file in the same directory.

Thanks!
