### ISSUE TITLE
How to get the normalized expression data and spot_id for the spots contained in each crade in the spatial trajectory, and how to visualize these spots.

### ISSUE THREAD

**Issue by tyaoi** [BiomedicalMachineLearning/stLearn#228]
Hi,

Thanks for the development of such a great analysis tool for ST.
I have successfully performed the spatial trajectory inference according to the tutorial for Visium. 

1. Here, I would like to show the expression trend of a particular gene along the trajectory, which is a sequence of clades, using a line plot.To do this, I need to get the normalized expression x spot_id matrix of the spots in each clade of the spatial trajectory, and the order of the spots along pseudo time.  How can I do this? 

2. Also, as shown in the tutorial, how can I visualize the spots corresponding to each clade on the tissue image?

3. I want to compare gene expression profiles between a spot that constitutes a clade and other spots in the cluster to which it belongs. To do so, how can I obtain the gene expression x spot ID matrix of all the spots belonging to a particular cluster?

Please provide me with solutions or suggestions.

tyaoi

**Comment by duypham2108** [comment]
I think all the question can be solved if you subset the `adata` object

1. Each clade includes multiple sub-clusters. You can subset the anndata based on `.obs.sub_cluster_labels`.
For example: extract a subset of adata that contains sub_cluster `6` and `16`
```
subset_adata = adata[adata.obs.sub_cluster_labels.isin(['6','16'])]
```
2. You can use the subset from 1. to visualize each clade. Or cropped the image by parameter `zoom_coord`, for example:
```
st.pl.cluster_plot(adata,use_label="louvain",
                   image_alpha=1,size=10,
                   zoom_coord=[1000,1400,1700,2100])
```
3. Similar to the first quesiton, you can extract by you cluster label column in `.obs` like `.obs.leiden` or `obs.louvain`
