### ISSUE TITLE
Problem with creating "stlearn object"

### ISSUE THREAD

**Issue by suvranath1** [BiomedicalMachineLearning/stLearn#232]
Hello,

I am trying to create my own "stlearn" object  with my own spatial spot count matrix and associated 3D coordinates (x,y and z). (also with 2D coordinates) 
However, when I try to create the "stlearn" object as per the tutorial mentioned here: https://stlearn.readthedocs.io/en/latest/tutorials/Read_any_data.html as

import stlearn as st
adata = st.create_stlearn(count=a,spatial=b,library_id="Th",scale=1, background_color="white")

It is giving me following error:

KeyError                                  Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key)
   3651         try:
-> 3652             return self._engine.get_loc(casted_key)
   3653         except KeyError as err:

~\Anaconda3\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

~\Anaconda3\lib\site-packages\pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'imagecol'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_19372\2878763128.py in <module>
      1 import stlearn as st
----> 2 adata = st.create_stlearn(count=a,spatial=b,library_id="Th",scale=1, background_color="white")

~\Anaconda3\lib\site-packages\stlearn\wrapper\read.py in create_stlearn(count, spatial, library_id, image_path, scale, quality, spot_diameter_fullres, background_color)
    634         scale = 2000 / max_coor
    635 
--> 636     adata.obs["imagecol"] = spatial["imagecol"].values * scale
    637     adata.obs["imagerow"] = spatial["imagerow"].values * scale
    638 

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   3759             if self.columns.nlevels > 1:
   3760                 return self._getitem_multilevel(key)
-> 3761             indexer = self.columns.get_loc(key)
   3762             if is_integer(indexer):
   3763                 indexer = [indexer]

~\Anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key)
   3652             return self._engine.get_loc(casted_key)
   3653         except KeyError as err:
-> 3654             raise KeyError(key) from err
   3655         except TypeError:
   3656             # If we have a listlike key, _check_indexing_error will raise

KeyError: 'imagecol'

I am pretty beginner with coding with python and any suggestions would be immensely helpful to me.

Thanks,
Suvra

**Comment by duypham2108** [comment]
Can you make sure the column in your `b` variable as a data frame contains the "imagecol" and "imagerow" columns? If it's not working, you can send me your code here and print the `a` and `b` here

**Comment by suvranath1** [comment]
Hello Duy Pham,

Thanks for your reply.

My count matrix looks like this:

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/ab1003d7-76a2-436b-a35c-b9e82740aa37)


And my coordinate matrix looks like this after changing my coordinate matrix’s x and y column with “imagecol” and “imagerow” respectively.
 
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/e5455cac-0d18-4016-b567-3131f2293cb5)

Now I can execute the command, but facing following issue:

-	When I try to plot the genes with 
st.pl.gene_plot(adata,gene_symbols="Gene_11", show_plot=True) , I cannot see anything in display. Do you have any suggestion?

-	When I tried with st.pl.gene_plot_interactive(adata), it works but the display is only in 2D. Can you also recommend me to plot the gene count in 3D?

Thank you so much for your suggestions & help.

Regards,
Suvra

**Comment by duypham2108** [comment]
For the first issue, you can add this line before you run the plotting function
```
%matplotlib inline
```

For the second question, we currently do not support 3D visualization. I recommend you use plotly for this purpose, they have a built-in function for 3D scatter plot. You can check it here https://plotly.com/python/3d-scatter-plots/

**Comment by suvranath1** [comment]
Hello Duy Pham,

It works now. Thank you once again for your suggestions!

Regards,
Suvra

**Comment by suvranath1** [comment]
One more follow up question Duy Pham,

My goal is to display the cluster information from my spatial transcriptomics analysis (that I have done in R) of individual cells in the spatial plot that I have done with this package.

I have successfully assign the Seurat cluster information to the numpy array and passed this cluster info to the **label.**

I am now trying to import Seurat Clusters and try to plot it with my **stlearn** object, but it gives me following error:

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/3dae6e51-17f5-408f-89fa-c736fcd82313)

Do you have any suggestion for this? 

Thank you once again!
