### ISSUE TITLE
Problem with plotting "Seurat Cluster" in "stlearn" object

### ISSUE THREAD

**Issue by suvranath1** [BiomedicalMachineLearning/stLearn#234]
My goal is to display the cluster information from my spatial transcriptomics analysis (that I have done in R) of individual cells in the spatial plot that I have done with this package.

I have successfully assign the Seurat cluster information to the numpy array and passed this cluster info to the **label.**

My data structure looks like this:

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/13954a96-64a8-4f6b-9e5b-c4913296c3f4)

and after passing the cluster info to the cells type, it looks like this:

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/5c1b9e20-f2cf-4304-8518-e3edf5eebae4)

I am now trying to import Seurat Clusters and try to plot it with my **stlearn** object, but it gives me following error:

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/3dae6e51-17f5-408f-89fa-c736fcd82313)

Do you have any suggestion for this? 

Thank you once again!

**Comment by duypham2108** [comment]
I suggest to convert it to Categorical type first and remove the previous color setting by

``
import pandas as pd
adata.obs["seurat"] = pd.Categorical(data.obs.seurat.values)
del adata.uns["seurat_colors"]
```

**Comment by suvranath1** [comment]
Thank you for your response.

I did that, and used **stlearn.pl.cluster_plot** with **use_label == "seurat"**, but it gave me following error:

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/1cfc547f-f5a7-4bd0-b43d-d4a62a53824e)

I tried modifying the source file that is mentioned here: https://stlearn.readthedocs.io/en/stable/_modules/stlearn/plotting/cluster_plot.html#cluster_plot

But with no success so far.

**Comment by duypham2108** [comment]
It should be `use_label="seurat"`

**Comment by suvranath1** [comment]
It gives me same indexing error :(

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/114509929/a6679956-7e90-4c3e-add1-fe4470aaba2d)

**Comment by duypham2108** [comment]
There are some of my suggestions 

- Try to update stlearn
- Import scanpy and use their sc.pl.spatial function to plot
- Run the delete again before you run the clustering function
