### ISSUE TITLE
Diagnostic plot - data does not have "nonzero-median"

### ISSUE THREAD

**Issue by Laura-Waechter** [BiomedicalMachineLearning/stLearn#237]
Dear all,

I am trying to use the function stlearn.pl.lr_diagnostics on my data, but I get back the exception: Inputted nonzero-median; must be one of ['n_spots', 'n_spots_sig', 'n_spots_sig_pval', 0]. I have been following this workflow: https://stlearn.readthedocs.io/en/latest/tutorials/stLearn-CCI.html#Diagnostic-plots.
It is not obvious to me where the nonzero-median column should come from, therefore I would appreciate some help.

Thanks in advance.

**Comment by BradBalderson** [comment]
Hey Laura,

I am wondering what `data.uns["lrfeatures"]` looks like? 

What was the code ran, prior to running stlearn.pl.lr_diagnostics?

Finally, are you using the latest version of stlearn? I think most likely it is a version issue.

**Comment by Laura-Waechter** [comment]
Hello,

when I run data.uns["lrfeatures"] the output is:
0                  nonzero-median zero-prop median_...
dtype: object
Prior to this, I run the code of the vignette: https://stlearn.readthedocs.io/en/latest/tutorials/stLearn-CCI.html but with a dataset that I had to read in with st.create_stlearn() and then assigned cell types with the following: https://squidpy.readthedocs.io/en/stable/external_tutorials/tutorial_vizgen_mouse_liver.html. 
The version of stlearn I use is 0.4.12
