### ISSUE TITLE
preprocessing steps

### ISSUE THREAD

**Issue by derekrusso** [BiomedicalMachineLearning/stLearn#244]
After reading all the tutorials, I think stLearn is a great tool for spatial downstream analysis !
But forgive me for asking silly questions (I am new to spatial omics analysis):

the datasets used in the tutorials all have preannotated information, either by deconvolution or label transfer.  However, stlearn currently do not offer cell type annotation function. Is it recommended to first annotate spots (eg. by tangram or seurat)? 
By applying the above pipeline, there seems problems regarding the preprocessing steps. (as both stlearn and seurat offer preprocessing, normalization, and clustering).

Is there a 'best practice' for analyzing spatial data by stlearn?

**Comment by duypham2108** [comment]
For any type of analysis, I suggest that you should keep the raw data (which might store in different layers of `anndata` object).
Currently, we don't have a best practice for preprocessing. You can transfer the result from other tools/software to a new anndata with your data and perform stlearn with it. It will be required a bit of hacking to the `anndata` object.

We will try to improve the tutorial and codes to support users using results from other tools as soon as we can.
