### ISSUE TITLE
"available_paths" not available

### ISSUE THREAD

**Issue by QuinceyLv** [BiomedicalMachineLearning/stLearn#245]
Hi, 
I was using stlearn 0.4.12:

`st.spatial.trajectory.pseudotime(adata_SME, eps=50, use_rep="X_pca", use_label = 'leiden', max_nodes = len(adata_SME.obs['leiden'].unique()))`

and I checked adata_SME.uns['available_paths'], choosed some paths to perform st.spatial.trajectory.pseudotimespace_global() and got error.

![企业微信截图_20230803161609](https://github.com/BiomedicalMachineLearning/stLearn/assets/28379444/7f65a857-3de4-46dc-856d-dfa71c71045f)

So what 'available_paths' means? or something went wrong when I process my data? Thanks.

**Comment by duypham2108** [comment]
Can you try to install the GitHub version? I fixed it but have uploaded it yet
