### ISSUE TITLE
about "st.pl.trajectory.tree_plot" problem

### ISSUE THREAD

**Issue by chang202308** [BiomedicalMachineLearning/stLearn#247]
hi ,I have some questions when using the "st.pl.trajectory.tree_plot" function
When I am in accordance with the operating steps at https://stlearn.readthedocs.io/en/latest/tutorials/Pseudo-time-space-tutorial.html
Execute the trajectory to st.pl.trajectory.tree_plot, and find that different from the example, there is no spatial picture below the trajectory tree.
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/142468923/063bf420-1ad8-463d-9509-7e4bebccbb40)

Below is the code I run, can you help to see what the problem is?
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/142468923/3ee05ee3-f9f0-47ee-9320-52e1d18f51ea)

stlearn running version '0.4.12'

**Comment by duypham2108** [comment]
Please use the function in this comment. We will try to fix it soon

https://github.com/BiomedicalMachineLearning/stLearn/issues/243#issuecomment-1657823079

**Comment by chang202308** [comment]
Thank so much.
It worked with the new code aboove.
I noticed that a new version was released yesterday, is this version a newer version than 0.4.12?  Did the version released yesterday solve the problem of tree_plot? (https://github.com/BiomedicalMachineLearning/stLearn/releases)
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/142468923/41775c95-f480-452c-aabc-e5eecc1975b8)

**Comment by duypham2108** [comment]
It has not solved this problem yet. I will update in the comment here when everything is ready

**Comment by chang202308** [comment]
Ok, thanks again and look forward to your update.

**Comment by chang202308** [comment]
hi ，I  got a new error when drawing the 3D trajectory plot in st.pl.trajectory.local_plot function, could you please look at it?
follow is my code:

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/142468923/14873ea8-3f70-46e5-91d0-4be7ed8bc346)
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/142468923/f735bea4-cd30-40a9-84d4-e470df2369fc)

**Comment by chang202308** [comment]
Hello. Sorry to bother you again. I have a confusion with stlearn trajectory analysis.
If I get mechanical clusters, but I don't know the differentiation relationship between them, so I don't know which cluster to set as the root cluster. Can stLearn automatically calculate and determine which cluster is the starting point? If there is such a function, how should the corresponding function and parameters be set?
Looking forward to your reply

**Comment by duypham2108** [comment]
We don't support it directly. There is an implementation of CytoTrace method from CellRank here

```
def finding_root_index(tmp_adata):
    num_exp_genes = np.array((tmp_adata.X > 0).sum(axis=1)).reshape(-1)
    gene_corr, _, _, _ = _correlation_test_helper(tmp_adata.X.T, num_exp_genes[:, None])
    tmp_adata.var["gene_corr"] = gene_corr

    # Use top 1000 genes rather than top 200 genes
    top_1000 = tmp_adata.var.sort_values(by="gene_corr", ascending=False).index[:1000]
    tmp_adata.var["correlates"] = False
    tmp_adata.var.loc[top_1000, "correlates"] = True
    corr_mask = tmp_adata.var["correlates"]
    imputed_exp = tmp_adata[:, corr_mask].X

    # Scale ct score
    cytotrace_score = np.mean(imputed_exp, axis=1)
    cytotrace_score -= np.min(cytotrace_score)
    cytotrace_score /= np.max(cytotrace_score)

    # Get the root index
    local_index = np.argmax(cytotrace_score)
    obs_name = tmp_adata.obs.iloc[local_index].name

    return np.where(tmp_adata.obs_names == obs_name)[0][0]
```
