### ISSUE TITLE
st.pl.cluster_plot

### ISSUE THREAD

**Issue by ZJU-TingYun** [BiomedicalMachineLearning/stLearn#252]
Thanks for your powerful tool. I have some problems with spatial trajectory plot. How to adjust the size of trajectory arrow? And wether can we plot partial trajectory arrows?

**Comment by duypham2108** [comment]
Can you check these parameters:

```
trajectory_node_size: Optional[int] = 10,
trajectory_alpha: Optional[float] = 1.0,
trajectory_width: Optional[float] = 2.5,
trajectory_edge_color: Optional[str] = "#f4efd3",
trajectory_arrowsize: Optional[int] = 17,
```

For the partial trajectory arrows, I think I haven't implemented it yet. One solution is to export pdf file and remove the unwanted trajectory from that.

Hope it helps
