### ISSUE TITLE
Dimension of 'distance' in LR permutation test

### ISSUE THREAD

**Issue by joan-yanqiong** [BiomedicalMachineLearning/stLearn#255]
Hi, 

I started started exploring xenium data and was trying out the tutorial. For the `st.tl.cci.run` function, one of the inputs is 'distance'. I was wondering what the dimension of that is. I saw that None means, immediate neighbours and 0 for within-spot. I don't have immediate neighbours, so I have to increase the distance. Is the distance just the number of spots in the grid?

**Comment by duypham2108** [comment]
The distance is the pixel length as the radius from each spot center. We will query all the spots within that radius
