### ISSUE TITLE
Allow saving tiles as PNG images in `stlearn.pp.tiling`

### ISSUE THREAD

**Issue by jbschiratti** [BiomedicalMachineLearning/stLearn#257]
Currently, `stlearn.pp.tiling` ([link](https://github.com/BiomedicalMachineLearning/stLearn/blob/3fe707a9b50f7a6ea15e80844609446aef446eb3/stlearn/image_preprocessing/image_tiling.py#L91C13-L91C40)) saves image tiles as JPEG files using:

```python
tile.save(out_tile, "JPEG")
```

With Pillow, as per [the documentation](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-saving), the default value of the JPG `quality` parameter is 75. 
In some cases, it might be preferable to save tiles using a _lossless_ image format such as PNG. 

What about allowing users to save tiles as PNG images instead?

I can submit a PR to add this feature.

**Comment by duypham2108** [comment]
It will be a good option. All contribution is welcome. Thank you
