### ISSUE TITLE
How to get the clade no.s after generating trajectory plot

### ISSUE THREAD

**Issue by rialc13** [BiomedicalMachineLearning/stLearn#261]
Hi. I am running the below code for creating trajectories -
```
st.spatial.trajectory.pseudotimespace_global(bdata,use_label="seurat_clusters",list_clusters=["4","13"])
st.pl.cluster_plot(bdata,use_label="seurat_clusters",show_trajectories=True,list_clusters=["4","13"],show_subcluster=True)
```
<img width="766" alt="image" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/77878787/5b519e3d-3c50-4283-a6e2-02dce72f2f70">

`tree_plot(bdata, use_label="seurat_clusters")`
<img width="604" alt="image" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/77878787/3f54bd23-f7fb-4b6d-aede-e86e62018006">

After I generate the tree plot, I get the clade number information. Can you tell me how to fetch the number of clades & the clade number from my anndata object itself? For eg, if my iroot = cluster 0, & my list_clusters = 4,13, what will be the command for fetching the clade information just for this trajectory?

**Comment by duypham2108** [comment]
The name of the clade will be the starting (after pseudoroot) node. Currently, we don't have any function to extract it automatically. You can manually extract them by every sub-clusters from "sub_cluster_labels" in `.obs`. For example `adata.obs[adata.obs.sub_cluster_labels.isin(["3","1"])` in your case

**Comment by rialc13** [comment]
Is there anyway we can get the clade information before generating the plot? For example, if I just run the function st.spatial.trajectory.pseudotimespace_global (not the st.pl.cluster_plot), how can I fetch the clade number?

**Comment by duypham2108** [comment]
You can extract the graph like this

```
import networkx as nx
from stlearn.utils import _read_graph
G = _read_graph(data,"PTS_graph")
G.remove_node(9999)
nx.draw_networkx(G)
```
