### ISSUE TITLE
save anndata object to h5ad file

### ISSUE THREAD

**Issue by rialc13** [BiomedicalMachineLearning/stLearn#262]
Hi,

After performing spatial trajectory analysis, I am trying to save the anndata object to h5ad file using the write_h5ad(file_name) function but am getting the following error -

<img width="622" alt="image" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/77878787/74b6097d-0c3d-4f1e-a242-33fbb09b2b06">

I googled the error & many people suggested removing the adata.raw layer. I did that (using del bdata.raw), still I get the following (new) error -

<img width="842" alt="image" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/77878787/01897af0-7de7-4c57-8b61-43af83d38c49">
<img width="833" alt="image" src="https://github.com/BiomedicalMachineLearning/stLearn/assets/77878787/ffad2eee-c723-4bae-bee8-e4e83b461f6e">

Can you please help? Thanks

**Comment by duypham2108** [comment]
It seems Anndata prevents saving it in the new version if the key in a dictionary has an int type. We will try to fix it soon.
One temporary solution is using pickle

```
# For saving
import pickle
with open('anndata.obj', 'wb') as fp:
    pickle.dump(data, fp)

# For loading
import pickle
with open('anndata.obj', 'rb') as fp:
    adata = pickle.load(fp)
```

**Comment by rialc13** [comment]
Thank you so much! This worked!

**Comment by rialc13** [comment]
Thank you so much! This worked!
