### ISSUE TITLE
ValueError in step 2 of CCI analysis

### ISSUE THREAD

**Issue by Rachel-qianqian** [BiomedicalMachineLearning/stLearn#264]
Dear developers：

As I ran code as follow, and added the path to"path_to_stlearn/tutorials/label_transfer_bc.csv" as you described in issue #142.
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/150638073/6a02b205-2aa8-4174-97c5-e986505efe36))

Then, I got the error as follow.
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/150638073/e3454b2d-dfaf-409d-97b6-1c62caac083b)

Hope you can tell me how to deal with it.

Sincerely! ：)

**Comment by duypham2108** [comment]
Can you add this line after the first line?
```
spot_mixtures = spot_mixtures.loc[data.obs_names]
```

**Comment by Rachel-qianqian** [comment]
Many thanks for your replying. I added this line as follow:
`spot_mixtures = pd.read_csv("path/label_transfer_bc.csv", index_col=0, sep='\t')
spot_mixtures = spot_mixtures.loc[data.obs_names]
labels = spot_mixtures.loc[:,'predicted.id'].values.astype(str)
spot_mixtures = spot_mixtures.drop(['predicted.id','prediction.score.max'],
                                   axis=1)
spot_mixtures.columns = [col.replace('prediction.score.', '')
                         for col in spot_mixtures.columns]` 

and it returned 
`KeyError: "['AAACGCCCGAGATCGG-1', 'GAAAGCAGTGCACTTT-1', 'GAAGGGCATAACCATG-1', 'GGGACCCGTATATCTT-1', 'GTTCCCGTAAACATAT-1', 'TAGATATGGACTGGAA-1', 'TGAGCAGTCGTGAAGT-1', 'TGTACCCGACCCTAAT-1', 'TTACGGTGTCACCGAG-1'] not in index"`

The data is derived from V1_Breast_Cancer_Block_A_Section_1 (2020-06-23). Did i do someting wrong? I will really appreciate it.
