### ISSUE TITLE
st.tl.cci.run "AttributeError: module 'numpy' has no attribute 'int'."

### ISSUE THREAD

**Issue by skim245** [BiomedicalMachineLearning/stLearn#265]
Dear stLearn, 

I'm getting an attribute error with stlearn == 0.4.11  numpy ==1.26.0 
and below is the error message I get. 

`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:

any suggestions ?

**Comment by duypham2108** [comment]
You can install the numpy to 1.22 by `pip install numpy==1.22` and do not need to worry about the version warning if it shows up.

**Comment by skim245** [comment]
@duypham2108 great it works without error!
