### ISSUE TITLE
Pseudo-time-space analysis problem

### ISSUE THREAD

**Issue by PIGAsHIT** [BiomedicalMachineLearning/stLearn#268]
`Traceback (most recent call last):
  File "/mnt/d/stlearn_env/lib/python3.10/site-packages/stlearn/app/source/forms/views.py", line 320, in run_psts
    st.spatial.trajectory.pseudotimespace_global(
TypeError: pseudotimespace_global() got an unexpected keyword argument 'w'
pseudotimespace_global() got an unexpected keyword argument 'w'`

As shown above, I don't quite understand why this error is occurring. Are there any directions or possibilities that I can modify? Thank you!

**Comment by duypham2108** [comment]
We categorize it to three different models: "spatial", "gene_expression" and "mixed" to prevent random weight input. You can try setting `model` parameter for those 3 options. For examples: `model="spatial`

**Comment by PIGAsHIT** [comment]
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/93385350/13550407-cb70-4bbe-a79a-687784173b44)
Thank you for your response. I am using your webapp service. As you mentioned, I have tried all three methods, but the same error still occurs.

**Comment by duypham2108** [comment]
I see. Sorry that we haven't updated it yet. I will try to fix it soon

**Comment by PIGAsHIT** [comment]
Hello, I would like to ask if the issue mentioned previously has been resolved. Additionally, if it has been fixed, where can I download the new version? Thank you :)

**Comment by duypham2108** [comment]
I just fixed it.
Please uninstall the previous version and install a version in master branch by

```
pip uninstall stlearn --yes
git clone https://github.com/BiomedicalMachineLearning/stLearn.git
cd stLearn
python setup.py install
```

**Comment by PIGAsHIT** [comment]
BIG THANKS!

Duy Pham ***@***.***>於 2023年12月15日 週五，02:19寫道：
