### ISSUE TITLE
Interactive stLearn: BokehJS 3.1.1 successfully loaded  but no picture seen

### ISSUE THREAD

**Issue by howtofindme** [BiomedicalMachineLearning/stLearn#269]
Really wonderful job， Thanks!

    When I follow your tutuial in https://stlearn.readthedocs.io/en/latest/tutorials/Interactive_plot.html. I did not find the interactive interface in my jupyterlab. Could you give me some suggestion?

![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/72066151/02c07ab3-7f4a-4fde-a5e6-d87c350c93f8)

Best,
Young

**Comment by duypham2108** [comment]
Currently, it only supports local computer jupyter notebook. So if you are using remote server to run jupyter then it won't work

**Comment by howtofindme** [comment]
> Currently, it only supports local computer jupyter notebook. So if you are using remote server to run jupyter then it won't work

Thanks for your timely reply,

As you suggest ,I have installed jupyter in local. but it throw me another error,could you give some suggestion?
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/72066151/7e269496-c8b5-4a83-abbf-0c582f6d259b)
Best,
Young

**Comment by howtofindme** [comment]
> > Currently, it only supports local computer jupyter notebook. So if you are using remote server to run jupyter then it won't work
> 
> Thanks for your timely reply,
> 
> As you suggest ,I have installed jupyter in local. but it throw me another error,could you give some suggestion? ![image](https://private-user-images.githubusercontent.com/72066151/290826328-7e269496-c8b5-4a83-abbf-0c582f6d259b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NDQ2NTEsIm5iZiI6MTcwMjY0NDM1MSwicGF0aCI6Ii83MjA2NjE1MS8yOTA4MjYzMjgtN2UyNjk0OTYtYzhiNS00YTgzLWFiYmYtMGM1ODJmNmQyNTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEyNDU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ZWFiMWJjODJjZmIyNjM0NjMzYzY4MTg5OWJhY2FjNmYyNjc5OWZkYjRiYjIxNmY0ZWZlZTBkMWE3YTE4NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1QyoyXktHHda9jlmj2GpqcxSVkVBqM1voeizN-wB3K0) Best, Young

even I change the ip location ,it still gives me errors:
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/72066151/fdcab581-67b4-4a62-8edd-c04236b09246)
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/72066151/e555df83-41f9-43d3-80b6-00284a44fcf3)
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/72066151/dad1498e-58a0-4ac2-91a4-80811ba5c1d5)

**Comment by duypham2108** [comment]
Can you run the juputer notebook or lab on the port :8888? I only setting for that default port

**Comment by howtofindme** [comment]
> Can you run the juputer notebook or lab on the port :8888? I only setting for that default port

Yes! You are right. Thanks for your kind reply. I have made it by running the juputer notebook or lab on the port :8888!

Best,
Young
