### ISSUE TITLE
stlearn CCI is not working  for multiple slides?

### ISSUE THREAD

**Issue by howtofindme** [BiomedicalMachineLearning/stLearn#270]
**Dear developer,
Thanks for your wonderful jobs!
I have learned from your [tutorials in Integration_multiple_datasets section.](https://stlearn.readthedocs.io/en/latest/tutorials/Integration_multiple_datasets.html) But I found the integrated object is not working correctly for [stLearn Cell-Cell Interaction Analysis](https://stlearn.readthedocs.io/en/latest/tutorials/stLearn-CCI.html)  when I run the following codes using the integrated data:**

>#Basic normalisation 
st.pp.filter_genes(data, min_cells=1)
st.pp.normalize_total(data) # NOTE: no log1p for CCI
![image](https://github.com/BiomedicalMachineLearning/stLearn/assets/72066151/ec43af11-a348-4f72-9c30-e1c3a9c76e13)
you can see the data.var becomes zero.

**Comment by duypham2108** [comment]
You should make sure 2 slides (samples) have to have the same set (or subset) of genes

**Comment by howtofindme** [comment]
> You should make sure 2 slides (samples) have to have the same set (or subset) of genes

Yes, you are right,solved, Thanks
