### ISSUE TITLE
Question abount integrating multiple spatial data with only spatial coordinates

### ISSUE THREAD

**Issue by cynthier** [BiomedicalMachineLearning/stLearn#274]
Hi, thank you so much for developing this useful tool.

I have the stereo-seq data with more than three replicates and I want to integate all of them to infer trajectory. Is it possible to change the coordinates according to my annotation without the images? 

Thank you in advance!

**Comment by duypham2108** [comment]
For the scope of this package, we don't support it. You can use some packages to align the spatial transcriptomic. Some of them will not require images

**Comment by cynthier** [comment]
@duypham2108  Thank you for your reply.
