### ISSUE TITLE
stlearn attributes not found

### ISSUE THREAD

**Issue by mvereten** [BiomedicalMachineLearning/stLearn#276]
Dear team,

I attempted to install the package, and that went well, I have the environment with stlearn package in it. Then I activate the environment and open up Python. I add the package path via sys and the stlearn seems to load ok, although it doesn't refer to an init__.py file, and then I get errors such as 'module 'stlearn' has no attribute 'tl' (same for 'pl'). It may be something to do with the path added, but I don't see what's wrong. Any ideas would be much appreciated. Thanks, M

**Comment by duypham2108** [comment]
Can you create a new environment and install by conda?
https://stlearn.readthedocs.io/en/latest/installation.html#install-by-anaconda
