### ISSUE TITLE
Single cell transcriptomic data for cell-cell communication

### ISSUE THREAD

**Issue by liangbolyu** [BiomedicalMachineLearning/stLearn#280]
Hi, I read the paper and the tutorial of your method. But it seems that your method can only fix the cell-cell communication on spots level. Could you please tell me how to use your method to do the cell-cell communication on single cell level data?

**Comment by BiomedicalMachineLearning** [comment]
You can use between spot mode CCI to analyse single-cell resolution interaction. One of our figures show that. If there are too many cells, to make the computation faster, you can apply the gridding option: https://stlearn.readthedocs.io/en/latest/tutorials/Xenium_CCI.html

**Comment by liangbolyu** [comment]
Hi, have you shown "between spot mode CCI to analyse single-cell resolution interaction" in your tutorial? Or where can I find it?

**Comment by BiomedicalMachineLearning** [comment]
in the link above, you can see: 

# Running the analysis #
st.tl.cci.run(grid, lrs,
                  min_spots = 20, #Filter out any LR pairs with no scores for less than min_spots
                  distance=None, # None defaults to spot+immediate neighbours; distance=0 for within-spot mode
                  n_pairs=1000, # Number of random pairs to generate; low as example, recommend ~10,000
                  n_cpus=None, # Number of CPUs for parallel. If None, detects & use all available.
                  )
