### ISSUE TITLE
Is it possible to run CCI in muti-sample?

### ISSUE THREAD

**Issue by yunbokai** [BiomedicalMachineLearning/stLearn#285]
Hi, I got an integrated ST data and I tried to use CCI function. When I ran `stats = ['lr_scores', 'p_vals', 'p_adjs', '-log10(p_adjs)']
fig, axes = plt.subplots(ncols=len(stats), figsize=(16,6))
for i, stat in enumerate(stats):
    st.pl.lr_result_plot(adata,
                         use_result=stat, 
                         use_lr=best_lr, 
                         show_color_bar=False, ax=axes[i])
    axes[i].set_title(f'{best_lr} {stat}')`
It occured ERROR  Found multiple possible libraries in `.uns['spatial']. Please specify. How to solve it?
Thanks.

**Comment by duypham2108** [comment]
Currently, we only support single library anndata only. You can create a new anndata object with a specific library and then run it again
