### ISSUE TITLE
Run stSME clustering without HE

### ISSUE THREAD

**Issue by rocketeer1998** [BiomedicalMachineLearning/stLearn#295]
Hi @quanaibn @BradBalderson @duypham2108 @jon-xu @xiao233333 , thanks for your awesome tool! I'd like to know whether I can run stSME without HE images at hand?

**Comment by xiao233333** [comment]
Hi @rocketeer1998, You are still able to use stSME normalisation. You can use spatial distance to normalise your data. Please see the attached code: 

```
st.spatial.SME.SME_normalize(data, use_data="raw", weights="physical_distance")
```
