### ISSUE TITLE
Having trouble understanding the cell cell interaction table

### ISSUE THREAD

**Issue by QiuYue117** [BiomedicalMachineLearning/stLearn#308]
![image](https://github.com/user-attachments/assets/cff62867-d549-435b-a66b-206852bad795)
hi! May I ask how do i interpret the columns of this result? I dont quite understand the difference between the significant column and the adjusted pvalue, how does it constitute to significant, and what does the adjusted pvalue mean?

Thank you so much!!

**Comment by BradBalderson** [comment]
n_spot_sig are the significant hotspots of ligand-receptor interactions, after adjusting p-values for multiple hypothesis testing (MHT). n_spots_sig_pval are the number of hotspots without the MHT correction (nominal p-values).
