### ISSUE TITLE
Spatial deconvolution visualization

### ISSUE THREAD

**Issue by jnmark** [BiomedicalMachineLearning/stLearn#68]
Hello,

I am trying to run the spatial deconvolution section using stLearn. However, I get the following error: 

AttributeError                            Traceback (most recent call last)
<ipython-input-8-8d3857e8d640> in <module>
      1 #Seurat-Label Transfer deconvolution
----> 2 st.add.auto_annotate(data, annotation_path = "/Users/jnmark/Work/Seurat/spatial/deconvolution_result.csv")
      3 st.pl.deconvolution_plot(data, threshold = 0.5)

AttributeError: module 'stlearn.add' has no attribute 'auto_annotate'

Seems like the auto_annotate function is not present in the documentation either. Could you please help me resolve this? Thanks!

**Comment by duypham2108** [comment]
Thanks for reporting this issue.

It will be fixed in the next update. You can use this source code instead of calling the function st.add.auto_annotate: https://github.com/BiomedicalMachineLearning/stLearn/blob/master/stlearn/adds/auto_annotate.py

**Comment by jnmark** [comment]
This worked out for me. Thank you so much!
