### ISSUE TITLE
unexpected argument 'font_size'

### ISSUE THREAD

**Issue by sokratiag** [BiomedicalMachineLearning/stLearn#69]
Hi, 

I am using stLearn to do some trajectory analysis and each time the function needs to access 'draw_networkx_edges()', it throws an 'unexpected argument 'font_size' error. I checked Networkx' documents and the 'draw_networkx_edges' function does not have a 'font_size' argument:

 draw_networkx_edges(G, pos, edgelist=None, width=1.0, edge_color='k', style='solid', alpha=None, arrowstyle='-|>', arrowsize=10, edge_cmap=None, edge_vmin=None, edge_vmax=None, ax=None, arrows=True, label=None, node_size=300, nodelist=None, node_shape='o', connectionstyle=None, min_source_margin=0, min_target_margin=0)

Are you using a different version of networkx or we do really need to remove that argument? 

Thanks!

**Comment by duypham2108** [comment]
Thanks for using our toolkit.
We use networkx 2.4. Which version of networkx do you use? 
Anyways, we will publish a new version (cleaner) next week.

Could you please install by the github master branch (uninstall the current version first).
Just make sure you can install, please clone the github then run this:
`python setup.py install`

**Comment by sokratiag** [comment]
thanks a lot for your help. I downgraded to netowrkx 2.4 and it works now!
