### ISSUE TITLE
Integrate other data platforms

### ISSUE THREAD

**Issue by hzaumsq** [BiomedicalMachineLearning/stLearn#85]
Hi author !
 I wonder how to Integrate with other data platforms like Seruat ？Also ，I need other platforms to analyse . can you give me any idea or suggestion.
Thanks!!

**Comment by duypham2108** [comment]
The current version of stLearn does not support converting to Seurat object.
We wrote this toolkit based on Scanpy, then I recommend you to use both stLearn (specific function) and Scanpy to analyze your data.

**Comment by BiomedicalMachineLearning** [comment]
Hi, for integration with other platforms, especially R-based platforms, you can conveniently convert stLearn anndata object to an R object (e.g. Seurat; and more generally to a SingleCellExperiment class) object, see here for an example using reticulate and Suerat Convert function  [https://satijalab.org/seurat/archive/v2.4/conversion_vignette.html](url) from R; and here for two-way conversions using the anndata2ri package  [https://github.com/theislab/anndata2ri](url)
