### ISSUE TITLE
Running portal

### ISSUE THREAD

**Issue by asmagen** [BiomedicalMachineLearning/stLearn#87]
I followed the Mac installation steps which completed successfully, but there's no instruction on how to run the portal. I tried the following which failed:
(stlearn) MAC:~ User1$ stlearn
Creating directory /Users/User1/Library/Application Support/bioservices 
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/stlearn/bin/stlearn", line 5, in <module>
    from stlearn.cli import main
  File "/usr/local/anaconda3/envs/stlearn/lib/python3.8/site-packages/stlearn/cli.py", line 3, in <module>
    import click
ModuleNotFoundError: No module named 'click'
Can you clarify how to get the GUI running or what's the problem here?
Thanks

**Comment by duypham2108** [comment]
Sorry that we haven't published the GUI version yet. It's still developing.
We will open it and notify you soon.

**Comment by asmagen** [comment]
I thought the manual is focused on the GUI. So it’s not published for general use?

**Comment by duypham2108** [comment]
This is software that belongs to a method paper. The GUI is an additional part of it.
We are improving it and hope we can publish the GUI next month (early or middle).
Stay tuned!

**Comment by BiomedicalMachineLearning** [comment]
Thanks for using the tool. Any user can download the GUI and use it anytime. It is still under very active development, so stay tuned (likely a large update next month). 
For now: you should follow the installation guide in here https://github.com/BiomedicalMachineLearning/stlearn_interactive. I suggest you create a conda environment, install stlearn via pip install -U (as in here: https://stlearn.readthedocs.io/en/latest/installation.html), then activate the environment, and within that environment do pip install bokeh, then within the  stlearn_interactive directory you can execute this command: bokeh serve --show stlearn
