### ISSUE TITLE
About 'label_transfer_bc.csv'

### ISSUE THREAD

**Issue by ChangliangWang** [BiomedicalMachineLearning/stLearn#90]
Dear Jon,

Sorry to bother you again, but I have a question about 'label_transfer_bc.csv'. I am wondering the format of the file (I didn't find the explanation about the file in the tutorial ). 
Thanks very much for your help.

Best wishes,
Changliang.

**Comment by jon-xu** [comment]
Hi Changliang,

The file you will use in st.add.labels is the label transfer result of Seurat v3.
So you need to find a reference dataset with cell types identified for each cell and integrate it with the ST dataset using Seurat and predict the cell types for each spot. (https://satijalab.org/seurat/archive/v3.0/integration.html)

Cheers,
Jon

**Comment by ChangliangWang** [comment]
Dear Jon,

I have label transfer result in the below format

the first column is 'barcode', the second column is 'predicted.id', and the third column is 'prediction.score.max'
[cid:1ba08f1b-301a-40e8-8567-e6abffced0d1]

However, I still encounter an error as below: 'KeyError: "['predicted.id' 'prediction.score.max'] not found in axis"'

Anywhere wrong with my label_transfer_bc.csv?

Thanks very much for your help

Best wishes,
Changliang.


________________________________
发件人: jon-xu <notifications@github.com>
发送时间: 2021年3月5日 11:32
收件人: BiomedicalMachineLearning/stLearn <stLearn@noreply.github.com>
抄送: Wang Changliang <yb67610@connect.um.edu.mo>; Author <author@noreply.github.com>
主题: Re: [BiomedicalMachineLearning/stLearn] About 'label_transfer_bc.csv' (#90)


Hi Changliang,

The file you will use in st.add.labels is the label transfer result of Seurat v3.
So you need to find a reference dataset with cell types identified for each cell and integrate it with the ST dataset using Seurat and predict the cell types for each spot. (https://satijalab.org/seurat/archive/v3.0/integration.html<https://urldefense.proofpoint.com/v2/url?u=https-3A__satijalab.org_seurat_archive_v3.0_integration.html&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=bhPcwygvMRH7vWVpUUxVrQ&m=PbRZOR99EAToje1YuNCw0u13kt3ejop0GUgJjRNuuPY&s=cqeyrKt5m2QehiF5U1Yadcn2lWkz_izAAlmKIbceea0&e=>)

Cheers,
Jon

―

**Comment by jon-xu** [comment]
Hi Changliang,

Could you please check the separation character of your csv? 
The default in st.add.labels is set to '\t', and you can change by using "sep" parameter.

e.g. st.add.labels('your_file.csv', sep=',')

Hope it helps.
Jon

**Comment by ChangliangWang** [comment]
Hi Jon,

It works. Thanks very much for your help.

BTW, there is no 'sep' parameter for st.add.labels when reading a 'csv' file in the tutorial. I thought the default delimiter is ','.

Thanks again for your help.

Best wishes,
Changliang.

________________________________
发件人: jon-xu <notifications@github.com>
发送时间: 2021年3月5日 12:57
收件人: BiomedicalMachineLearning/stLearn <stLearn@noreply.github.com>
抄送: Wang Changliang <yb67610@connect.um.edu.mo>; Author <author@noreply.github.com>
主题: Re: [BiomedicalMachineLearning/stLearn] About 'label_transfer_bc.csv' (#90)


Hi Changliang,

Could you please check the separation character of your csv?
The default in st.add.labels is set to '\t', and you can change by using "sep" parameter.

e.g. st.add.labels('your_file.csv', sep=',')

Hope it helps.
Jon

―

**Comment by jon-xu** [comment]
Cool, we'll update the documentations, thanks!

**Comment by ChangliangWang** [comment]
Dear Jon,

Sorry to bother you again. But I have a question about the format of the data.uns['label_transfer']. My data.uns['label_transfer'] is an empty dataframe as below:
Empty DataFrame
Columns: []
Index: [AAACAAGTATCTCCCA-1, AAACCGGAAATGTTAA-1, AAACCGGGTAGGTACC-1, AAACCGTTCGTCCAGG-1, AATAACACTAGAACAA-1, ...]
[2323 rows x 0 columns].

There should something wrong here, as when I run 'Count cell type diversity for between-spot mode', all the cells are very similar as shown below:
![image](https://user-images.githubusercontent.com/25944188/110234433-6520b980-7f65-11eb-8f44-288eb12b732e.png)

Any suggestions. Thanks very much for your help.

Best wishes,
Changliang.

**Comment by jon-xu** [comment]
Hi Changliang,

could you please send your label transfer result to my email address: jun.xu@uq.edu.au?

Thanks,
Jon

**Comment by jon-xu** [comment]
Just to put a note here after checking the data, you need the full Seurat label transfer result to feed into stLearn for cell type detection.

**Comment by sailseem** [comment]
Dear Jon,
   I would like to ask the same question, cause i am a really new user here. Maybe it's quite silly, but hope you can help me out.
This is my label transfer file from seurat, when I did the st.add.labels(data,"precitions.csv")，i got KeyError: "['predicted.id' 'prediction.score.max'] not found in axis".   I tried like you said, sep=' ' or seq='\t', or seq=' ',but none of this works.  So, could you help me with this? Thank you very much.
![image](https://user-images.githubusercontent.com/72428172/118415680-d2de1580-b679-11eb-9338-7f0a2213eb4d.png)

**Comment by jon-xu** [comment]
Hi Sailseem,

Are you sure this result comes from Seurat TransferData?
It looks more like SPOTlight result for me.

If it's from SPOTlight, you can use below statements to add in the cell type predictions:

labels = pd.read_csv('<your result file>.csv', index_col = 0, sep=',').T
data.uns["label_transfer"] = labels.drop(['max'], axis=1)

**Comment by sailseem** [comment]
Dear Jon,
  Thanks for pointing that out, it works now. But I got another issue, can you help?
![image](https://user-images.githubusercontent.com/72428172/118582635-aac9e180-b761-11eb-977b-a8963c57598f.png)

I might take too much time, sorry for this

**Comment by sailseem** [comment]
Dear Jon,
   Thank you for your help, and one more thing, when I did the st.pl.het_plot(data, use_het='cci_het'), I have no idea why all the dot express the same, it looks like that, am I doing anything wrong? 


![image](https://user-images.githubusercontent.com/72428172/118585826-a99bb300-b767-11eb-87e3-dee402aa9575.png)

**Comment by jon-xu** [comment]
Hi,
We count cell types in the neighbourhood which has a prediction probability larger than 0.2.
Please take some example spots and check the cell type predictions of its neighbours.
Hope it helps.
Jon
