### ISSUE TITLE
Old Spatial Transcriptomics data

### ISSUE THREAD

**Issue by jiazhao97** [BiomedicalMachineLearning/stLearn#98]
Hi,

Thank you for this nice tool! 

Would you provide more detailed documents or examples on the inputs of the function **st.ReadOldST**? I find [this tutorial](https://stlearn.readthedocs.io/en/latest/Working-with-Old-Spatial-Transcriptomics-data.html) very useful, but I can not figure out how to correctly input the old ST data.

To be specific, I want to visualize [this dataset](https://www.spatialresearch.org/resources-published-datasets/doi-10-1016-j-cell-2019-11-025/) which is an old ST dataset. But I do not know how to use **st.ReadOldST** to visualize it. It is very helpful if you provide an example for this function using one of the dataset from [the web](https://www.spatialresearch.org/resources-published-datasets/), because this web page contains rich resources of old ST data.

Thanks in advance!

Best,
Jia

**Comment by duypham2108** [comment]
Thanks for using our tool.
The problem with the old ST data is that it doesn't have a standard format then you need to reformat it a little bit.
I will show you how to read the developmental heart:

An example here is `ST_Sample_4.5-5PCW_1` sample. 
You need to use 4 files: `ST_Sample_4.5-5PCW_1_HE_small.jpg`, `spot_data-all-ST_Sample_4.5-5PCW_1.tsv` and `filtered_matrix.tsv` 

**Step 1:** Extract the `ST_Sample_4.5-5PCW_1` count matrix from `filtered_matrix.tsv`
An example code that extracts 1x prefix ID and removes the prefix 1x from `filtered_matrix.tsv`:

```
import pandas as pd
counts = pd.read_table("[PATH_TO_filtered_matrix.tsv]",index_col=0).T
# Subset the dataframe with the "1x" prefix index (barcode)
sample_1 = counts[counts.index.str.startswith("1x")]
# Remove the prefix from the index
sample_1.index = list(map(lambda x: x[2:],sample_1.index))
# Save it to a new tsv file
sample_1.to_csv("ST_Sample_4.5-5.tsv",sep="\t")
```
The purpose here is to make sure the barcode is consistent with the barcode in `spot_data-all-ST_Sample_4.5-5PCW_1.tsv` file. I think most of the dataset has this problem then please format it before you use st.ReadOldST

**Step 2:** You can use st.ReadOldST now to read those data:

```
data = st.ReadOldST(count_matrix_file="[PATH_TO_ST_Sample_4.5-5.tsv]",
                    spatial_file="[PATH_TO_ST_spot_data-all-ST_Sample_4.5-5PCW_1.tsv]",
                    image_file="[PATH_TO_ST_Sample_4.5-5PCW_1_HE_small.jpg]")
``` 

**Update**: I also found a bug with a different number of columns in the spot information files then please install the github version by clone this repo and install with:

```
# remove the old version
pip uninstall stlearn
# install a new update
python setup.py install
```

**Comment by jiazhao97** [comment]
Thanks a lot!
